import { Horse } from '@/types/Horse'
import { newDate } from 'app/lib/utils'
import dynamic from 'next/dynamic'
import { Foaled } from '@/types/Foaled'

const HL = dynamic(() => import('@/components/HorseLink'), { ssr: false })

const FLORRIES_CUP: Horse = {
  name: 'フロリースカツプ',
  pedigreeName: 'Florries Cup',
  id: 'florries-cup',
  breed: 'サラブレッド種',
  foaled: new Foaled('1907'),
  died: '1927',
  sex: 'female',
  sire: 'Florizel',
  dam: 'Stirrup Cup',
  breeder: 'W. C. Whitney',
  color: '黒鹿毛',
  children: [
    {
      pedigreeName: '第二フロリースカツプ',
      id: 'dai2-florries-cup',
      breed: 'サラブレッド種',
      foaled: new Foaled(newDate(1909, 3, 24)),
      died: '1932.06 斃死', // 『サラブレッド血統書 第1巻』p.440
      sex: 'female',
      sire: 'インタグリオー(GB)',
      dam: 'フロリースカツプ',
      breeder: '小岩井農場（岩手県岩手郡雫石村）',
      color: '黒鹿毛',
      raceStats: {
        total: { runs: 0, wins: 0 },
        divisions: [],
      },
      children: [
        {
          name: 'プロデアー',
          pedigreeName: 'フロリカルチユアー',
          id: 'florrie-culture',
          breed: 'サラブレッド種',
          foaled: new Foaled(newDate(1918, 3, 20)),
          died: '1938年以降 転売不明', // 『サラブレッド血統書 第1巻』p.437
          sex: 'female',
          sire: 'ルーヂゲーア(GB)',
          dam: '第二フロリースカツプ',
          breeder: '小岩井農場（岩手県岩手郡雫石村）',
          color: '黒鹿毛',
          children: [
            {
              name: 'レパード',
              pedigreeName: 'ナスノー',
              id: 'nasunoo',
              breed: 'サラブレッド種',
              sex: 'female',
              color: '鹿毛',
              foaled: new Foaled(newDate(1929, 5, 4)),
              died: '1952.08.24 死亡',
              sire: 'ロイヂユール(GB)',
              dam: 'フロリカルチユアー',
              breeder: '大平市太郎（岩手県盛岡市上小路）',
              retired: '1935年',
              owner: '？→廣田盛雄→坂本芳太郎',
              jockey: '荒井貢',
              raceStats: {
                total: { runs: 8, wins: 1 },
                divisions: [
                  {
                    type: 'central',
                    stats: { flat: { runs: 6, wins: 1 }, jump: { runs: 2, wins: 0 } },
                  },
                  {
                    type: 'local',
                    stats: { flat: { runs: 0, wins: 0 }, jump: { runs: 0, wins: 0 } },
                  },
                ],
              },
              prizeMoney: {
                total: '850円',
              },
              raceResults: [
                {
                  date: newDate(1933, 5, 28),
                  racecourse: '小倉',
                  race: '新呼馬優勝',
                  displayRace: '新呼馬優勝',
                  distance: '2000',
                  grade: 'empire_cs',
                  entry: '8',
                  result: '8',
                },
              ],
              children: [
                {
                  name: 'ナスノタケ',
                  id: 'nasunotake',
                  breed: 'サラブレッド種',
                  sex: 'male',
                  color: '鹿毛',
                  foaled: new Foaled('1946'),
                  sire: 'マルタケ',
                  dam: 'ナスノー',
                  breeder: 'マルタケ牧場（北海道沙流郡門別村）',
                  retired: '1951.03.22 地方競馬',
                  owner: '長峰常次郎',
                  trainer: '伊藤勝吉',
                  jockey: '清田十一',
                  raceStats: {
                    total: { runs: 40, wins: 15 },
                    divisions: [
                      {
                        type: 'central',
                        stats: { flat: { runs: 36, wins: 14 }, jump: { runs: 4, wins: 1 } },
                      },
                    ],
                  },
                  prizeMoney: {
                    total: '3,387,600円',
                    central: '3,387,600円',
                  },
                  raceResults: [
                    {
                      date: newDate(1949, 11, 3),
                      racecourse: '京都',
                      race: '菊花賞',
                      displayRace: '菊花賞',
                      distance: '3000',
                      grade: 'national_big8',
                      entry: '6',
                      result: '5',
                    },
                    {
                      date: newDate(1950, 4, 16),
                      racecourse: '京都',
                      race: '京都記念（春）',
                      displayRace: '京都記念（春）',
                      distance: '3000',
                      grade: 'national_grade',
                      entry: '7',
                      result: '3',
                    },
                    {
                      date: newDate(1950, 5, 7),
                      racecourse: '阪神',
                      race: '阪神記念（春）',
                      displayRace: '阪神記念（春）',
                      distance: '2600',
                      grade: 'national_grade',
                      entry: '?',
                      result: '1',
                    },
                    {
                      date: newDate(1950, 6, 4),
                      racecourse: '京都',
                      race: '天皇賞（春）',
                      displayRace: '天皇賞（春）',
                      distance: '3200',
                      grade: 'national_big8',
                      entry: '9',
                      result: '2',
                    },
                    {
                      date: newDate(1950, 10, 1),
                      racecourse: '阪神',
                      race: '阪神記念（秋）',
                      displayRace: '阪神記念（秋）',
                      distance: '2600',
                      grade: 'national_grade',
                      entry: '7',
                      result: '3',
                    },
                    {
                      date: newDate(1950, 11, 3),
                      racecourse: '東京',
                      race: '天皇賞（秋）',
                      displayRace: '天皇賞（秋）',
                      distance: '3200',
                      grade: 'national_big8',
                      entry: '10',
                      result: '7',
                    },
                    {
                      date: newDate(1950, 11, 26),
                      racecourse: '阪神',
                      race: 'チヤレンジカツプ（ハンデ）',
                      displayRace: 'チャレンジC',
                      distance: '2400',
                      grade: 'national_grade',
                      entry: '9',
                      result: '5',
                    },
                  ],
                  summary: '泡と消えた「父子4代・帝室御賞典馬」の夢',
                  details: `
父**マルタケ**の馬主が運営するマルタケ牧場で1946年に生まれる。1949年2回小倉で初出走。菊花賞こそ6頭立て5着に沈んだものの、年間で8勝を挙げる活躍を見せた。翌1950年には京都記念（春）で3着。阪神では特ハンと阪神記念（春）で1着。1段飛ばしで着順を上げて重賞勝利をつかみ取った。

余勢を駆って天皇賞（春）へ向かうナスノタケにはある大記録が懸かっていた。曾祖父**ラシカツター**、祖父**ハクリユウ**、父**マルタケ**による父子3代帝室御賞典（天皇賞）制覇、それを「父子4代」に更新する挑戦である。ラシカツターとハクリユウが勝ったのは統一前の「帝室御賞典」ではあるものの、それを除いても**マルタケ**との「史上初の父子制覇」となる。3000mの京都記念（春）での好走、上がり調子、血統背景、そして往年のファンの夢が託されたのだろうか、ナスノタケは1番人気に推された。

当日の馬場は稍重。勝利したのは9頭立て8番人気の**オーエンス**で、ナスノタケは3馬身離された2着に終わった。再び挑んだ天皇賞（秋）では前目につけるも直線失速し7着に敗れた。翌年には障害に転向し4戦1勝、その春に地方競馬へ転出。ここにナスノタケの夢は潰えた。その後の行方は分かっていない。

なお、なぜか資料上の性別が不安定で『サラブレッド血統書 第3巻』や『国営競馬統計 昭和28年』などでは牝馬と表記されている。

現在、天皇賞の第1回は日本競馬会による統一後の1937年「帝室御賞典（秋）」とされているため、マルタケの勝利が「父子3代天皇賞勝利」と称されることはない。それを初めて成し遂げたのは50年後の**メジロマックイーン**であり、奇しくも**オーエンス**と同じ**オーグメント**の牝系だった。
// ここはマルタケのとこでいいかも`,
                },
              ],
            },
          ],
        },
        {
          name: 'キングフロラー',
          pedigreeName: '第十一コイワヰ',
          id: 'king-flora',
          breed: 'サラブレッド種',
          sex: 'male',
          color: '栗毛',
          foaled: new Foaled(newDate(1923, 4, 8)),
          sire: 'コイワヰ',
          dam: '第二フロリースカツプ',
          breeder: '小岩井農場（岩手県岩手郡雫石村）',
          retired: '1932年秋季（年齢超過）',
          owner: '平岡廣高（トクホ）',
          trainer: '尾形景造',
          jockey: '尾形景造',
          raceStats: {
            total: { runs: 57, wins: 16 },
            divisions: [
              {
                type: 'central',
                stats: { flat: { runs: 45, wins: 13 }, jump: { runs: 12, wins: 3 } },
              },
              { type: 'local', stats: { flat: { runs: 0, wins: 0 }, jump: { runs: 0, wins: 0 } } },
            ],
          },
          raceResults: [
            {
              date: newDate(1927, 11, 27),
              racecourse: '目黒',
              race: '内国産新馬優勝',
              displayRace: '新馬優勝',
              distance: '1m1/4',
              grade: 'empire_cs',
              entry: '3',
              result: '2',
            },
            {
              date: newDate(1928, 4, 7),
              racecourse: '鳴尾',
              race: '各内国産馬古馬聯合',
              displayRace: '阪神連合（春）',
              distance: '3200',
              grade: 'empire_2mile',
              entry: '8',
              result: '4',
            },
            {
              date: newDate(1928, 4, 29),
              racecourse: '目黒',
              race: '帝室御賞典',
              displayRace: '帝室御賞典（東京・春）',
              distance: '1800',
              grade: 'empire_cup',
              entry: '5',
              result: '1',
            },
            {
              date: newDate(1928, 5, 5),
              racecourse: '目黒',
              race: '優勝内国産馬聯合',
              displayRace: '連合二哩（春）',
              distance: '3200',
              grade: 'empire_2mile',
              entry: '6',
              result: '4',
            },
            {
              date: newDate(1928, 5, 19),
              racecourse: '根岸',
              race: '横濱特別',
              displayRace: '横浜特別（春）',
              distance: '3200',
              grade: 'empire_2mile',
              entry: '9',
              result: '4',
            },
            {
              date: newDate(1928, 7, 21),
              racecourse: '中山',
              race: '下総特殊ハンデキャップ',
              displayRace: '特ハン',
              distance: '2000',
              grade: 'empire_cs',
              entry: '5',
              result: '1',
            },
            {
              date: newDate(1928, 7, 29),
              racecourse: '中山',
              race: '各内国産馬優勝',
              displayRace: '優勝',
              distance: '2400',
              grade: 'empire_cs',
              entry: '6',
              result: '1',
            },
            {
              date: newDate(1928, 9, 19),
              racecourse: '福島',
              race: '福島市賞典 各内国産馬特殊ハンデキャップ',
              displayRace: '特ハン',
              distance: '2000',
              grade: 'empire_cs',
              entry: '6',
              result: '2',
            },
            {
              date: newDate(1928, 9, 23),
              racecourse: '福島',
              race: '各内国産古馬優勝',
              displayRace: '優勝',
              distance: '2400',
              grade: 'empire_cs',
              entry: '5',
              result: '1',
            },
            {
              date: newDate(1928, 10, 14),
              racecourse: '目黒',
              race: '各内外国産古馬',
              displayRace: '二哩一分（東京・大礼）',
              distance: '3400',
              grade: 'empire_2m1f',
              entry: '4',
              result: '2',
            },
            {
              date: newDate(1928, 11, 3),
              racecourse: '根岸',
              race: 'オールカマーハンデキャップ',
              displayRace: 'オールカマーハンデ',
              distance: '2000',
              grade: 'empire_cs',
              entry: '10',
              result: '5',
            },
            {
              date: newDate(1928, 11, 10),
              racecourse: '根岸',
              race: '横濱特別',
              displayRace: '横浜特別（秋）',
              distance: '3200',
              grade: 'empire_2mile',
              entry: '7',
              result: '5',
            },
            {
              date: newDate(1929, 5, 11),
              racecourse: '根岸',
              race: 'オールカマーハンデキャップ',
              displayRace: 'オールカマーハンデ',
              distance: '2000',
              grade: 'empire_cs',
              entry: '8',
              result: '4',
            },
            {
              date: newDate(1929, 9, 21),
              racecourse: '福島',
              race: '各内国産古馬特殊ハンデキャップ',
              displayRace: '特ハン',
              distance: '2000',
              grade: 'empire_cs',
              entry: '4',
              result: '1',
            },
            {
              date: newDate(1929, 9, 29),
              racecourse: '福島',
              race: '各内国産古馬優勝',
              displayRace: '優勝',
              distance: '2400',
              grade: 'empire_cs',
              entry: '4',
              result: '1',
            },
            {
              date: newDate(1929, 10, 18),
              racecourse: '中山',
              race: '各内国産馬特殊ハンデキャップ',
              displayRace: '特ハン',
              distance: '2000',
              grade: 'empire_cs',
              entry: '8',
              result: '6',
            },
            {
              date: newDate(1929, 11, 18),
              racecourse: '目黒',
              race: '各内国産古馬',
              displayRace: '二哩一分（秋）',
              distance: '3400',
              grade: 'empire_2m1f',
              entry: '5',
              result: '3',
            },
            {
              date: newDate(1930, 3, 30),
              racecourse: '中山',
              race: '障碍優勝',
              displayRace: '障害優勝',
              distance: '2800',
              grade: 'empire_cs',
              entry: '11',
              result: '中止',
            },
            {
              date: newDate(1930, 11, 23),
              racecourse: '目黒',
              race: '障碍優勝',
              displayRace: '障害優勝',
              distance: '3300',
              grade: 'empire_cs',
              entry: '8',
              result: '2',
            },
            {
              date: newDate(1930, 12, 14),
              racecourse: '京都',
              race: '障碍優勝',
              displayRace: '障害優勝',
              distance: '3200',
              grade: 'empire_cs',
              entry: '8',
              result: '7',
            },
          ],
          details: `
1923年に小岩井農場で誕生。両親ともに小岩井農場産という生粋の小岩井血統だった。デビューは4歳（旧5歳）になった1927年秋の東京とかなり遅い。翌年春には**エキスオン**・**ヘンペツキー**とそれぞれアタマ差クビ差の大接戦を演じ、その末に帝室御賞典（東京・春）の栄誉を勝ち取った。その後も勝利を重ね7歳までに13勝。障害に転向した8歳時にも3勝を挙げ、年齢制限となる10歳まで健康に走り続けた。また雨に強く、当時まことしやかに噂されていた「小岩井の馬は雨が苦手」という風説を打破した逸話が伝えられている。

10歳という高齢まで現役であったが、引退後には河西郡帯広町の六郎田武次の所有で「第十一コイワヰ」の名で種牡馬入り。のちに根室郡根室町・枳殻光次郎に購買され少なくとも1935年までは民間種牡馬を務め、いくらかの産駒を残したようである。


（戦績にある優勝戦の日付は「開催最終日」と仮定したものであり、不確実）`,
        },
      ],
    },
    {
      name: 'フロリスカツプ',
      pedigreeName: '第三フロリースカツプ',
      id: 'dai3-florries-cup',
      breed: 'サラブレッド種',
      sex: 'female',
      color: '鹿毛',
      foaled: new Foaled(newDate(1911, 4, 19)),
      died: '1933.08.18 斃死',
      sire: 'インフオーメーシヨン(GB)',
      dam: 'フロリースカツプ',
      breeder: '小岩井農場（岩手県岩手郡雫石村）',
      owner: '平出喜三郎（多賀一）',
      raceStats: {
        total: {},
        divisions: [],
      },
      raceResults: [
        {
          date: newDate(1914, 11, 8),
          racecourse: '目黒',
          race: '帝室御賞典',
          displayRace: '帝室御賞典（東京・秋）',
          distance: '1m',
          grade: 'empire_cup',
          entry: '9',
          result: '9',
        },
        {
          date: newDate(1915, 5, 2),
          racecourse: '目黒',
          race: '帝室御賞典',
          displayRace: '帝室御賞典（東京・春）',
          distance: '1m',
          grade: 'empire_cup',
          entry: '7',
          result: '1',
        },
      ],
      summary: '御賞典拝受と激動の五日間',
      details: `
旧4歳となった1914年の春、フロリスカツプは平出喜三郎（二代目）によって購入された。平出は函館競馬倶楽部の理事で、北海道函館区船見町（現在の函館市船見町）出身の政治家。実業家としても知られ、函館に平出農場を経営していた。函館に移ったフロリスカツプの調教を担当したのは続秀太郎。続は平出の義弟にして平出農場場長・調教師・騎手を兼任しており、1913年には**プレツチーポリー**に騎乗して帝室御賞典（東京・秋）を勝利していた。

同年秋には目黒競馬場に出場するも結果は芳しくなく、帝室御賞典（東京・秋）では**ハナビシ**の9着に敗れている。それでも更なる調教と成長を積んで翌1915年の春に再び上京。初日の内国産馬競走（1マイル）を差し切って勝利し、2日目の帝室御賞典（東京・春）に出走した。レースは7頭立て、初日の内国産新呼馬を勝った**ベストマン**と人気を分け合う形になる。発走前にはかなり入れ込む様子を見せていたが、スタートを決めて先頭に立つとそのままベストマンの追い込みを凌ぎ切り、3馬身差で逃げ切ってこのレースを制した。

この日、御賞典の賞品である銀製花盛器授与のために東伏見宮依仁親王が競馬場を訪れていた。戻った依仁親王の報告を受けた大正天皇は、詳しく聞くうちにフロリスカツプに興味を示した。大正天皇は以前より馬に通じていた上、ちょうど4月・5月の4日間で馬術の天覧（天皇直々の観覧）が行われていたこともあり、あれよあれよと話が進んでフロリスカツプの天覧が決まった。レースから僅か2日後、天覧馬術最終日の5月4日にフロリスカツプは吹上御苑で天皇と対面。関係者にとってはこれまでにない栄誉であっただろう。

それから2日後の5月6日早朝、目黒競馬場での調教騎乗中にそれは起こった。前足の管（かん、膝と球節の間の部分）に後ろ脚の蹄を誤ってぶつけてしまい亀裂骨折を発症、フロリスカツプの競走生活は思わぬ形で終わりを告げた。帝室御賞典の勝利から僅か5日目のことだった。

引退後は馬主の平出が所有する平出農場（北海道亀田郡湯の川村）で繁殖入り。1930年に事業に失敗した平出が牧場を手放し「湯ノ川牧場」と改称された後も繁殖生活を続け、1933年夏に旧23歳で死亡した。直後の9月に湯ノ川牧場は前川太郎兵衛らに譲渡。顧問を続けていた続もこれを機に湯ノ川を離れ、他の馬たちも手放された。なお、ラストクロップの**マークイス**はのちに帝室御賞典（東京・春）を母子制覇、牝系も2000年代まで続いた。`,
      citation: [
        'ワイ生「噫フロリスカツプ」『日本之産馬 5(6)』pp.44-46',
        '『中央獣医会雑誌 28(7)』p.41',
        '「イレネーを運んだ男 続秀太郎」『日本馬事協会 70年の歩み』pp.110-111',
        '「ヒラデエナモールド」『サラブレツド系統種牡馬名簿 第1巻』p.51',
        '「主禁」http://shukin.starfree.jp/BBS_LOG.htm',
      ],
      children: [
        {
          name: 'マークイス',
          formerPedigreeName: 'フロリス',
          id: 'marquis',
          breed: 'サラブレッド種',
          sex: 'male',
          color: '黒鹿毛',
          foaled: new Foaled('1933'),
          sire: 'ヒラデエナモールド',
          dam: '第三フロリースカツプ',
          breeder: '前川牧場（北海道函館市旭岡）',
          retired: '1939.02 乗用',
          owner: '前川太郎兵衛（カノウ）',
          trainer: '鈴木信太郎',
          jockey: '石毛彦次郎',
          raceStats: {
            total: { runs: 28, wins: 10 },
            divisions: [
              {
                type: 'central',
                stats: { flat: { runs: 28, wins: 10 }, jump: { runs: 0, wins: 0 } },
              },
              { type: 'local', stats: { flat: { runs: 0, wins: 0 }, jump: { runs: 0, wins: 0 } } },
            ],
          },
          prizeMoney: {
            total: '30,100円',
          },
          raceResults: [
            {
              date: newDate(1936, 5, 24),
              racecourse: '根岸',
              race: '新呼馬優勝',
              displayRace: '新馬優勝',
              distance: '2200',
              grade: 'empire_cs',
              entry: '8',
              result: '7',
            },
            {
              date: newDate(1936, 10, 10),
              racecourse: '中山',
              race: '古呼馬特殊ハンデキャップ',
              displayRace: '特ハン',
              distance: '2200',
              grade: 'empire_cs',
              entry: '14',
              result: '7',
            },
            {
              date: newDate(1936, 11, 1),
              racecourse: '根岸',
              race: '帝室御賞典',
              displayRace: '帝室御賞典（横浜・秋）',
              distance: '2000',
              grade: 'empire_cup',
              entry: '4',
              result: '4',
            },
            {
              date: newDate(1936, 11, 22),
              racecourse: '東京',
              race: '帝室御賞典',
              displayRace: '帝室御賞典（東京・秋）',
              distance: '2000',
              grade: 'empire_cup',
              entry: '5',
              result: '5',
            },
            {
              date: newDate(1937, 3, 27),
              racecourse: '中山',
              race: '古呼馬特殊ハンデキャップ',
              displayRace: '特ハン',
              distance: '2200',
              grade: 'empire_cs',
              entry: '16',
              result: '8',
            },
            {
              date: newDate(1937, 4, 18),
              racecourse: '東京',
              race: '帝室御賞典',
              displayRace: '帝室御賞典（東京・春）',
              distance: '2000',
              grade: 'empire_cup',
              entry: '5',
              result: '1',
            },
            {
              date: newDate(1937, 5, 8),
              racecourse: '根岸',
              race: 'オールカマーハンデキヤツプ',
              displayRace: 'オールカマーH',
              distance: '2200',
              grade: 'empire_cs',
              entry: '11',
              result: '3',
            },
            {
              date: newDate(1937, 6, 19),
              racecourse: '福島',
              race: '古呼馬特殊ハンデキャップ',
              displayRace: '特ハン',
              distance: '2200',
              grade: 'empire_cs',
              entry: '7',
              result: '5',
            },
            {
              date: newDate(1937, 6, 27),
              racecourse: '福島',
              race: '各古馬優勝',
              displayRace: '優勝',
              distance: '2600',
              grade: 'empire_cs',
              entry: '5',
              result: '1',
            },
            {
              date: newDate(1937, 11, 28),
              racecourse: '東京',
              race: '目黒記念',
              displayRace: '目黒記念（秋）',
              distance: '3400',
              grade: 'jrs_grade',
              entry: '6',
              result: '1',
            },
          ],
          details: `
1933年に誕生。生産は函館の前川牧場となっているが、これは函館の湯ノ川牧場を1933年9月に譲り受けたもの。湯ノ川牧場の前身・平出農場を創設した平出喜三郎はマークイスの両親の所有者でもあるため、事実上湯ノ川牧場の産といってもいいだろう。

1936年の春に4歳でデビュー。本格化したのは翌年からで、まず春に帝室御賞典（東京・春）を勝利。日本競馬協会による統一前最後の帝室御賞典で、母第三フロリースカツプ（競走名**フロリスカツプ**）との母子制覇を達成した。秋には目黒記念（秋）を勝ったほか、特ハン2勝・優勝1回という好成績を残した。翌1938年は初戦の中山特ハンで2着となるも、そこから怪我で休養に入る。しかしその怪我が癒えることはなく、最終的に1938年いっぱいで引退を余儀なくされた。引退後は乗馬になったと記録されている。

また、上記の休養期間中にあたる1937年の6月～8月にオリンピックに向けた馬術候補選手の強化合宿が中山競馬場で行われ、その候補馬として本馬と**カブト**が日本国際馬術協会に譲渡されたという。これがマークイスの引退事由だったのかははっきりしないが、その夏以降マークイスが1度も出走しなかった事実とは矛盾しない。あるいは記録上の抹消理由「乗用」がそれを指すのかもしれない。`,
          citation: ['『競馬と馬券の實際知識 昭和13年度版』p.441'],
        },
      ],
    },
    {
      pedigreeName: '第四フロリースカツプ',
      id: 'dai4-florries-cup',
      breed: 'サラブレッド種',
      foaled: new Foaled(newDate(1912, 4, 4)),
      died: '1939.10.06. 斃死', // 『サラブレッド血統書 第1巻』p.442, 『サラブレッド系種牡馬名簿 第1巻』p.33
      sex: 'female',
      sire: 'インタグリオー(GB)',
      dam: 'フロリースカツプ',
      breeder: '小岩井農場（岩手県岩手郡雫石村）',
      color: '黒鹿毛',
      children: [
        {
          name: 'フロラーカツプ',
          pedigreeName: 'フロリスト',
          id: 'florist',
          breed: 'サラブレッド種',
          sex: 'female',
          color: '栗毛',
          foaled: new Foaled(newDate(1919, 4, 27)),
          died: '1943.05.05 死亡',
          sire: 'ガロン(GB)',
          dam: '第四フロリースカツプ',
          breeder: '小岩井農場（岩手県岩手郡雫石村）',
          retired: '1925年春季以降',
          owner: '高井治兵衛→平岡廣高（トクホ）',
          jockey: '尾形景造→柴田寛治',
          raceStats: {
            total: { runs: 21, wins: 10 },
            divisions: [
              {
                type: 'central',
                stats: { flat: { runs: 21, wins: 10 }, jump: { runs: 0, wins: 0 } },
              },
              { type: 'local', stats: { flat: { runs: 0, wins: 0 }, jump: { runs: 0, wins: 0 } } },
            ],
          },
          prizeMoney: {
            total: '14,241円',
          },
          raceResults: [
            {
              date: newDate(1923, 11, 18),
              racecourse: '福島',
              race: '内国産新呼馬優勝',
              displayRace: '新馬優勝',
              distance: '1m1f',
              grade: 'empire_cs',
              entry: '2',
              result: '1',
            },
            {
              date: newDate(1923, 12, 16),
              racecourse: '目黒',
              race: '帝室御賞典',
              displayRace: '帝室御賞典（東京・秋）',
              distance: '1m2f',
              grade: 'empire_cup',
              entry: '10',
              result: '3',
            },
            {
              date: newDate(1923, 12, 23),
              racecourse: '目黒',
              race: '各内国産馬優勝',
              displayRace: '優勝',
              distance: '1m6f',
              grade: 'empire_cs',
              entry: '6',
              result: '4',
            },
            {
              date: newDate(1924, 5, 3),
              racecourse: '目黒',
              race: '優勝内国産馬聯合',
              displayRace: '連合二哩（春）',
              distance: '2m',
              grade: 'empire_2mile',
              entry: '8',
              result: '1',
            },
            {
              date: newDate(1924, 5, 17),
              racecourse: '福島',
              race: '福島市賞典 内国産馬「特殊ハンデキャップ」',
              displayRace: '特ハン',
              distance: '1m2f',
              grade: 'empire_cs',
              entry: '8',
              result: '3',
            },
            {
              date: newDate(1924, 5, 25),
              racecourse: '福島',
              race: '各内国産馬優勝',
              displayRace: '優勝',
              distance: '1m4f',
              grade: 'empire_cs',
              entry: '7',
              result: '3',
            },
            {
              date: newDate(1924, 10, 11),
              racecourse: '福島',
              race: '福島市賞典 各内国産馬特殊「ハンデキャップ」',
              displayRace: '特ハン',
              distance: '1m2f',
              grade: 'empire_cs',
              entry: '4',
              result: '1',
            },
            {
              date: newDate(1924, 10, 19),
              racecourse: '福島',
              race: '各内国産馬優勝',
              displayRace: '優勝',
              distance: '1m4f',
              grade: 'empire_cs',
              entry: '5',
              result: '1',
            },
            {
              date: newDate(1924, 11, 1),
              racecourse: '根岸',
              race: 'オールカマーハンデキヤツプ',
              displayRace: 'オールカマーH',
              distance: '1m1f',
              grade: 'empire_cs',
              entry: '8',
              result: '5',
            },
            {
              date: newDate(1924, 11, 9),
              racecourse: '根岸',
              race: '各内国産馬優勝',
              displayRace: '優勝',
              distance: '1m2f',
              grade: 'empire_cs',
              entry: '5',
              result: '2',
            },
            {
              date: newDate(1924, 11, 16),
              racecourse: '目黒',
              race: '帝室御賞典',
              displayRace: '帝室御賞典（東京・秋）',
              distance: '1m1f',
              grade: 'empire_cup',
              entry: '6',
              result: '1',
            },
            {
              date: newDate(1924, 11, 23),
              racecourse: '目黒',
              race: '各内国産馬優勝',
              displayRace: '優勝',
              distance: '1m6f',
              grade: 'empire_cs',
              entry: '6',
              result: '1',
            },
          ],
          children: [
            {
              name: 'タマロツク',
              pedigreeName: '第貮フロリスト',
              id: 'dai2-florist',
              breed: 'サラブレッド種',
              foaled: new Foaled(newDate(1927, 4, 10)),
              died: '1945年以降転売不明', // 血統書データサービスメニュー、凪的電脳賽馬
              sex: 'female',
              sire: 'ラシカツター(GB)',
              dam: 'フロリスト',
              breeder: '小岩井農場（岩手県岩手郡雫石村）',
              color: '栗毛',
              raceStats: {
                total: { runs: 0, wins: 0 }, // 『競馬必勝の基礎 種馬と競走馬篇』
                divisions: [],
              },
              children: [
                {
                  name: 'フロリストモア',
                  pedigreeName: 'フロラヴアース',
                  id: 'floraverse',
                  breed: 'サラブレッド種',
                  foaled: new Foaled(newDate(1936, 3, 1)),
                  died: '1949 転売不明', // 血統書データサービスメニュー
                  sex: 'female',
                  sire: 'シアンモア(GB)',
                  dam: '第貮フロリスト',
                  breeder: '小岩井農場（岩手県岩手郡雫石村）',
                  color: '鹿毛',
                  raceStats: {
                    total: { runs: 21, wins: 6 }, // 『母馬別競走成績書』p.558
                    divisions: [
                      {
                        type: 'central',
                        stats: { flat: { runs: 21, wins: 6 }, jump: { runs: 0, wins: 0 } },
                      },
                      {
                        type: 'local',
                        stats: { flat: { runs: 0, wins: 0 }, jump: { runs: 0, wins: 0 } },
                      },
                    ],
                  },
                  prizeMoney: {
                    total: '10,770円', // 『登録馬名簿 昭和16年』p.62
                  },
                },
              ],
            },
            {
              name: 'ハクリユウ',
              formerPedigreeName: '第弐ラシデヤー',
              id: 'hakuryu',
              breed: 'サラブレッド種',
              sex: 'male',
              color: '栗毛',
              foaled: new Foaled(newDate(1928, 4, 24)),
              died: '不詳（1950年以降）',
              sire: 'ラシデヤー',
              dam: 'フロリスト',
              breeder: '小岩井農場（岩手県岩手郡雫石村）',
              retired: '1932年11月 繁殖',
              owner: '新井八郎→吉田善助',
              trainer: '北郷五郎',
              jockey: '中村一雄・稲葉秀男',
              raceStats: {
                total: { runs: 31, wins: 13 },
                divisions: [
                  {
                    type: 'central',
                    stats: { flat: { runs: 31, wins: 13 }, jump: { runs: 0, wins: 0 } },
                  },
                  {
                    type: 'local',
                    stats: { flat: { runs: 0, wins: 0 }, jump: { runs: 0, wins: 0 } },
                  },
                ],
              },
              prizeMoney: {
                total: '54,560円',
              },
              raceResults: [
                {
                  date: newDate(1931, 9, 18),
                  racecourse: '福島',
                  race: '特ハン',
                  displayRace: '特ハン',
                  distance: '2000',
                  grade: 'empire_cs',
                  entry: '11',
                  result: '10',
                },
                {
                  date: newDate(1931, 10, 25),
                  racecourse: '根岸',
                  race: '帝室御賞典',
                  displayRace: '帝室御賞典（横浜・秋）',
                  distance: '2000',
                  grade: 'empire_cup',
                  entry: '7',
                  result: '2',
                },
                {
                  date: newDate(1931, 11, 3),
                  racecourse: '根岸',
                  race: '橫濱特別',
                  displayRace: '横浜特別（秋）',
                  distance: '3200',
                  grade: 'empire_2mile',
                  entry: '5',
                  result: '1',
                },
                {
                  date: newDate(1931, 11, 14),
                  racecourse: '目黒',
                  race: '特ハン',
                  displayRace: '特ハン',
                  distance: '2000',
                  grade: 'empire_cs',
                  entry: '8',
                  result: '1',
                },
                {
                  date: newDate(1931, 11, 15),
                  racecourse: '目黒',
                  race: '帝室御賞典',
                  displayRace: '帝室御賞典（東京・秋）',
                  distance: '2000',
                  grade: 'empire_cup',
                  entry: '6',
                  result: '1',
                },
                {
                  date: newDate(1931, 11, 22),
                  racecourse: '目黒',
                  race: '各内国産古馬聯合',
                  displayRace: '連合二哩（秋）',
                  distance: '3200',
                  grade: 'empire_2mile',
                  entry: '5',
                  result: '1',
                },
                {
                  date: newDate(1931, 12, 6),
                  racecourse: '京都',
                  race: '古呼馬優勝',
                  displayRace: '優勝',
                  distance: '2600',
                  grade: 'empire_cs',
                  entry: '5',
                  result: '2',
                },
                {
                  date: newDate(1932, 3, 26),
                  racecourse: '中山',
                  race: '特ハン',
                  displayRace: '特ハン',
                  distance: '2000',
                  grade: 'empire_cs',
                  entry: '8',
                  result: '1',
                },
                {
                  date: newDate(1932, 3, 27),
                  racecourse: '中山',
                  race: '中山四千米',
                  displayRace: '中山四千米',
                  distance: '4000',
                  grade: 'empire_grade',
                  entry: '7',
                  result: '1',
                },
                {
                  date: newDate(1932, 4, 16),
                  racecourse: '目黒',
                  race: '特ハン',
                  displayRace: '特ハン',
                  distance: '2000',
                  grade: 'empire_cs',
                  entry: '10',
                  result: '2',
                },
                {
                  date: newDate(1932, 4, 18),
                  racecourse: '目黒',
                  race: '目黑記念',
                  displayRace: '目黒記念（春）',
                  distance: '3400',
                  grade: 'empire_grade',
                  entry: '3',
                  result: '1',
                },
                {
                  date: newDate(1932, 5, 7),
                  racecourse: '根岸',
                  race: 'オールカマーＨ',
                  displayRace: 'オールカマーH',
                  distance: '2000',
                  grade: 'empire_cs',
                  entry: '7',
                  result: '2',
                },
                {
                  date: newDate(1932, 5, 22),
                  racecourse: '根岸',
                  race: '優勝呼馬',
                  displayRace: '優勝',
                  distance: '2400',
                  grade: 'empire_cs',
                  entry: '4',
                  result: '3',
                },
              ],
            },
            {
              name: 'ハクセツ',
              formerPedigreeName: '第四シアンモア',
              id: 'hakusetsu-1929',
              linkName: 'ハクセツ(1929)',
              breed: 'サラブレッド種',
              sex: 'male',
              color: '鹿毛',
              foaled: new Foaled(newDate(1929, 4, 1)),
              sire: 'シアンモア(GB)',
              dam: 'フロリスト',
              breeder: '小岩井農場（岩手県岩手郡雫石村）',
              retired: '12632',
              owner: '安藤権次郎→羽田牧場→マルタケ牧場',
              trainer: '田中和一郎',
              jockey: '田中和一郎',
              raceStats: {
                total: { runs: 27, wins: 13 },
                divisions: [
                  {
                    type: 'central',
                    stats: { flat: { runs: 27, wins: 13 }, jump: { runs: 0, wins: 0 } },
                  },
                  {
                    type: 'local',
                    stats: { flat: { runs: 0, wins: 0 }, jump: { runs: 0, wins: 0 } },
                  },
                ],
              },
              prizeMoney: {
                total: '71,661円',
              },
              raceResults: [
                {
                  date: newDate(1932, 4, 24),
                  racecourse: '目黒',
                  race: '東京優駿大競走',
                  displayRace: '東京優駿',
                  distance: '2400',
                  grade: 'empire_derby',
                  entry: '19',
                  result: '6',
                },
                {
                  date: newDate(1932, 10, 17),
                  racecourse: '根岸',
                  race: '優勝呼馬',
                  displayRace: '優勝',
                  distance: '2400',
                  grade: 'empire_cs',
                  entry: '6',
                  result: '2',
                },
                {
                  date: newDate(1932, 10, 22),
                  racecourse: '目黒',
                  race: '各古馬特ハン',
                  displayRace: '特ハン',
                  distance: '2000',
                  grade: 'empire_cs',
                  entry: '8',
                  result: '1',
                },
                {
                  date: newDate(1932, 10, 30),
                  racecourse: '目黒',
                  race: '農林省賞典',
                  displayRace: '連合二哩（秋）',
                  distance: '3200',
                  grade: 'empire_2mile',
                  entry: '5',
                  result: '2',
                },
                {
                  date: newDate(1932, 11, 3),
                  racecourse: '目黒',
                  race: '各古馬優勝',
                  displayRace: '優勝',
                  distance: '2600',
                  grade: 'empire_cs',
                  entry: '5',
                  result: '1',
                },
                {
                  date: newDate(1932, 11, 12),
                  racecourse: '鳴尾',
                  race: '農林省賞典',
                  displayRace: '阪神連合（秋）',
                  distance: '3200',
                  grade: 'empire_2mile',
                  entry: '5',
                  result: '1',
                },
                {
                  date: newDate(1933, 3, 26),
                  racecourse: '中山',
                  race: '五歳馬特別',
                  displayRace: '中山五歳馬特別（春）',
                  distance: '2800',
                  grade: 'empire_grade',
                  entry: '7',
                  result: '2',
                },
                {
                  date: newDate(1933, 4, 3),
                  racecourse: '中山',
                  race: '呼馬優勝',
                  displayRace: '優勝',
                  distance: '2600',
                  grade: 'empire_cs',
                  entry: '6',
                  result: '1',
                },
                {
                  date: newDate(1933, 4, 15),
                  racecourse: '目黒',
                  race: '各古馬特ハン',
                  displayRace: '特ハン',
                  distance: '2000',
                  grade: 'empire_cs',
                  entry: '7',
                  result: '4',
                },
                {
                  date: newDate(1933, 4, 17),
                  racecourse: '目黒',
                  race: '目黒記念',
                  displayRace: '目黒記念（春）',
                  distance: '3400',
                  grade: 'empire_grade',
                  entry: '4',
                  result: '3',
                },
                {
                  date: newDate(1933, 5, 7),
                  racecourse: '根岸',
                  race: '帝室御賞典',
                  displayRace: '帝室御賞典（横浜・春）',
                  distance: '2000',
                  grade: 'empire_cup',
                  entry: '6',
                  result: '2',
                },
                {
                  date: newDate(1933, 5, 14),
                  racecourse: '根岸',
                  race: '横浜特別',
                  displayRace: '横浜特別（春）',
                  distance: '3200',
                  grade: 'empire_2mile',
                  entry: '5',
                  result: '2',
                },
                {
                  date: newDate(1933, 10, 7),
                  racecourse: '根岸',
                  race: 'オールカマーハンデキヤツプ',
                  displayRace: 'オールカマーH',
                  distance: '2000',
                  grade: 'empire_cs',
                  entry: '9',
                  result: '1',
                },
                {
                  date: newDate(1933, 10, 8),
                  racecourse: '根岸',
                  race: '帝室御賞典',
                  displayRace: '帝室御賞典（横浜・秋）',
                  distance: '2000',
                  grade: 'empire_cup',
                  entry: '5',
                  result: '1',
                },
                {
                  date: newDate(1933, 10, 15),
                  racecourse: '根岸',
                  race: '横浜特別',
                  displayRace: '横浜特別（秋）',
                  distance: '3200',
                  grade: 'empire_2mile',
                  entry: '4',
                  result: '1',
                },
                {
                  date: newDate(1933, 10, 28),
                  racecourse: '中山',
                  race: '古呼馬特ハン',
                  displayRace: '特ハン',
                  distance: '2000',
                  grade: 'empire_cs',
                  entry: '12',
                  result: '1',
                },
                {
                  date: newDate(1933, 11, 5),
                  racecourse: '中山',
                  race: '中山秋季五歳馬特別',
                  displayRace: '中山五歳馬特別（秋）',
                  distance: '3200',
                  grade: 'empire_grade',
                  entry: '4',
                  result: '3',
                },
                {
                  date: newDate(1933, 11, 11),
                  racecourse: '中山',
                  race: '呼馬優勝',
                  displayRace: '優勝',
                  distance: '2600',
                  grade: 'empire_cs',
                  entry: '8',
                  result: '4',
                },
                {
                  date: newDate(1933, 11, 20),
                  racecourse: '東京',
                  race: '目黒記念',
                  displayRace: '目黒記念（秋）',
                  distance: '3400',
                  grade: 'empire_grade',
                  entry: '5',
                  result: '1',
                },
                {
                  date: newDate(1933, 11, 25),
                  racecourse: '東京',
                  race: '五歳馬特別',
                  displayRace: '五歳馬特別（秋）',
                  distance: '2400',
                  grade: 'empire_grade',
                  entry: '11',
                  result: '1',
                },
                {
                  date: newDate(1934, 3, 24),
                  racecourse: '中山',
                  race: '古呼馬特ハン',
                  displayRace: '特ハン',
                  distance: '2000',
                  grade: 'empire_cs',
                  entry: '7',
                  result: '7',
                },
                {
                  date: newDate(1934, 4, 3),
                  racecourse: '中山',
                  race: '中山四千米',
                  displayRace: '中山四千米',
                  distance: '4000',
                  grade: 'empire_grade',
                  entry: '4',
                  result: '1',
                },
              ],
              summary: '五歳秋に覚醒した晩成の名馬',
              details: `
1929年に小岩井農場で誕生。父は名種牡馬**シアンモア**、母は牡馬相手に連合二哩と帝室御賞典を勝った**フロリスト**という超名血のもとに生まれた。さらにはデビュー直前の1931年秋、1歳上の半兄・**ハクリユウ**が連合二哩と帝室御賞典を連勝。ハクセツにかかる期待の大きさは想像に難くない。

果たして1932年の春にデビューし、中山の新呼馬で3着。東京で迎えた2戦目は**ワカタカ**に10馬身差をつけられての2着となる。3戦目には第一回東京優駿大競走（後の日本ダービー）に出走、4番人気6着と再び**ワカタカ**の前に敗れた。その後は休養して未勝利のまま秋開催を迎える。秋は横浜（日本レース倶楽部）で始動、初戦を1着で飾りこれが初勝利となる。東京では特ハンに斤量52kgで出走すると、同期の名牝**シラヌヒ**を破って優勝。余勢を駆って挑んだ農林省賞典（連合二哩）では再び**ワカタカ**に敗れて2着となったが、続く各古馬優勝戦で**アスコツト**・**ロビンオー**らを下して初優勝を果たした。次週は阪神に遠征し農林省賞典に出走。堂々の一番人気に推される中、雨上がりの不良馬場をレコードタイムで駆け抜けた。2着**アサヤス**に大差をつける圧勝だった。

5歳になった1933年、初戦の中山春季五歳馬特別は**ゼンソ**の2着。平場と呼馬優勝を勝利し、春の中山で2度目の優勝を果たす。しかしそれからは特ハン4着、目黒記念（春）3着、帝室御賞典（横浜・春）2着、横浜特別（春）2着と勝ちきれない競馬が続いた。相手には同期の葦毛馬**ハクコウ**とダービー馬**ワカタカ**、4月に中山四千米を勝って調子を上げてきた**アスコツト**が立ちはだかっていた。

秋になり、ハクセツの鞍上は石毛彦次郞から田中和一郎に再度乗り替わり。秋初戦に横浜の名物競走・オールカマーハンデキヤツプを選ぶとこれを圧勝し、さらに帝室御賞典（横浜・秋）、横浜特別（秋）、古呼馬特ハン（コースレコード）と怒涛の4連勝を飾る。ハクコウとワカタカへのリベンジも果たした。続く中山秋季五歳馬特別ではハクコウの3着、呼馬優勝ではワカタカの4着に敗れるも、東京に替わって目黒記念（秋）と五歳馬特別（秋）を連勝。この秋シーズンだけで8戦6勝（うち特別競走5勝）、28.755円を稼ぎあげる大活躍だった。

翌年も現役を続行するも、中山の特ハンで72kgという酷量を背負って最下位7着に惨敗してしまう。これが契機となってかハクセツはこの春限りでの引退を決定。ラストランの中山四千米では単勝支持率62.3%、単勝1.35倍の1番人気に応えて4馬身差で優勝。有終の美を飾ってターフを去った。

引退後は北海道沙流郡門別村の羽田牧場で種牡馬入り。種付け数は伸びず産駒から活躍馬は出なかった。昭和15年にマルタケ牧場に改称された際も、既に種付け数は0ながら引き続き繋養されたと伝わるがその後についてはわかっていない。`,
            },
            {
              name: 'スターカツプ',
              formerPedigreeName: '第参フロリスト',
              id: 'star-cup',
              breed: 'サラブレッド種',
              sex: 'female',
              color: '鹿毛',
              foaled: new Foaled(newDate(1930, 3, 30)),
              died: '1952.06.24 死亡',
              sire: 'シアンモア(GB)',
              dam: 'フロリスト',
              breeder: '小岩井農場（岩手県岩手郡雫石村）',
              retired: '1935年春季 繁殖',
              raceStats: {
                total: { runs: 22, wins: 12 },
                divisions: [
                  {
                    type: 'central',
                    stats: { flat: { runs: 22, wins: 12 }, jump: { runs: 0, wins: 0 } },
                  },
                  {
                    type: 'local',
                    stats: { flat: { runs: 0, wins: 0 }, jump: { runs: 0, wins: 0 } },
                  },
                ],
              },
              prizeMoney: {
                total: '47,684円',
              },
              raceResults: [
                {
                  date: newDate(1933, 10, 7),
                  racecourse: '鳴尾',
                  race: '新呼馬優勝',
                  displayRace: '新馬優勝',
                  distance: '2000',
                  grade: 'empire_cs',
                  entry: '5',
                  result: '1',
                },
                {
                  date: newDate(1933, 11, 5),
                  racecourse: '小倉',
                  race: '古呼馬（優勝）',
                  displayRace: '優勝',
                  distance: '2400',
                  grade: 'empire_cs',
                  entry: '8',
                  result: '1',
                },
                {
                  date: newDate(1933, 12, 25),
                  racecourse: '京都',
                  race: '古呼馬優勝',
                  displayRace: '優勝',
                  distance: '2600',
                  grade: 'empire_cs',
                  entry: '8',
                  result: '2',
                },
                {
                  date: newDate(1934, 1, 7),
                  racecourse: '鳴尾',
                  race: '帝室御賞典',
                  displayRace: '帝室御賞典（阪神・春）',
                  distance: '2000',
                  grade: 'empire_cup',
                  entry: '5',
                  result: '2',
                },
                {
                  date: newDate(1934, 1, 14),
                  racecourse: '鳴尾',
                  race: '農林省賞典',
                  displayRace: '阪神連合（春）',
                  distance: '3200',
                  grade: 'empire_2mile',
                  entry: '7',
                  result: '1',
                },
                {
                  date: newDate(1934, 4, 1),
                  racecourse: '京都',
                  race: '古呼馬特ハン',
                  displayRace: '特ハン',
                  distance: '2000',
                  grade: 'empire_cs',
                  entry: '7',
                  result: '1',
                },
                {
                  date: newDate(1934, 4, 3),
                  racecourse: '京都',
                  race: '牝馬聯合',
                  displayRace: '牝馬連合（春）',
                  distance: '3200',
                  grade: 'empire_2mile',
                  entry: '5',
                  result: '3',
                },
                {
                  date: newDate(1934, 4, 15),
                  racecourse: '京都',
                  race: '古呼馬優勝',
                  displayRace: '優勝',
                  distance: '2600',
                  grade: 'empire_cs',
                  entry: '5',
                  result: '1',
                },
                {
                  date: newDate(1934, 5, 18),
                  racecourse: '小倉',
                  race: '古呼馬特ハン',
                  displayRace: '特ハン',
                  distance: '2000',
                  grade: 'empire_cs',
                  entry: '7',
                  result: '1',
                },
                {
                  date: newDate(1934, 5, 20),
                  racecourse: '小倉',
                  race: '帝室御賞典',
                  displayRace: '帝室御賞典（小倉・春）',
                  distance: '2000',
                  grade: 'empire_cup',
                  entry: '6',
                  result: '1',
                },
                {
                  date: newDate(1934, 11, 23),
                  racecourse: '京都',
                  race: '古呼馬特ハン',
                  displayRace: '特ハン',
                  distance: '2000',
                  grade: 'empire_cs',
                  entry: '6',
                  result: '6',
                },
                {
                  date: newDate(1934, 12, 9),
                  racecourse: '京都',
                  race: '古呼馬優勝',
                  displayRace: '優勝',
                  distance: '2600',
                  grade: 'empire_cs',
                  entry: '5',
                  result: '2',
                },
                {
                  date: newDate(1934, 12, 14),
                  racecourse: '鳴尾',
                  race: '各古馬特ハン',
                  displayRace: '特ハン',
                  distance: '2000',
                  grade: 'empire_cs',
                  entry: '6',
                  result: '5',
                },
              ],
            },
            {
              name: 'アカイシダケ',
              formerPedigreeName: '第拾五シアンモア',
              id: 'akaishidake',
              breed: 'サラブレッド種',
              sex: 'male',
              color: '鹿毛',
              foaled: new Foaled(newDate(1932, 2, 17)),
              died: '1944年 廃用',
              sire: 'シアンモア(GB)',
              dam: 'フロリスト',
              breeder: '小岩井農場（岩手県岩手郡雫石村）',
              retired: '1937.02 繁殖',
              owner: '大倉喜七郎→鹿児島種馬所（農林省）',
              trainer: '尾形景造',
              jockey: '尾形景造',
              raceStats: {
                total: { runs: 27, wins: 11 },
                divisions: [
                  {
                    type: 'central',
                    stats: { flat: { runs: 27, wins: 11 }, jump: { runs: 0, wins: 0 } },
                  },
                  {
                    type: 'local',
                    stats: { flat: { runs: 0, wins: 0 }, jump: { runs: 0, wins: 0 } },
                  },
                ],
              },
              prizeMoney: {
                total: '64,742.50円',
              },
              raceResults: [
                {
                  date: newDate(1935, 4, 29),
                  racecourse: '東京',
                  race: '東京優駿大競走',
                  displayRace: '東京優駿',
                  distance: '2400',
                  grade: 'empire_derby',
                  entry: '11',
                  result: '2',
                },
                {
                  date: newDate(1935, 5, 5),
                  racecourse: '東京',
                  race: '新呼馬優勝',
                  displayRace: '新馬優勝',
                  distance: '2300',
                  grade: 'empire_cs',
                  entry: '6',
                  result: '1',
                },
                {
                  date: newDate(1935, 5, 12),
                  racecourse: '根岸',
                  race: '帝室御賞典',
                  displayRace: '帝室御賞典（横浜・春）',
                  distance: '2000',
                  grade: 'empire_cup',
                  entry: '4',
                  result: '2',
                },
                {
                  date: newDate(1935, 10, 12),
                  racecourse: '中山',
                  race: '古呼馬特ハン',
                  displayRace: '特ハン',
                  distance: '2200',
                  grade: 'empire_cs',
                  entry: '9',
                  result: '2',
                },
                {
                  date: newDate(1935, 10, 17),
                  racecourse: '中山',
                  race: '中山四歳馬特別',
                  displayRace: '中山四歳馬特別',
                  distance: '2400',
                  grade: 'empire_grade',
                  entry: '11',
                  result: '2',
                },
                {
                  date: newDate(1935, 10, 27),
                  racecourse: '中山',
                  race: '呼馬優勝',
                  displayRace: '優勝',
                  distance: '2600',
                  grade: 'empire_cs',
                  entry: '6',
                  result: '1',
                },
                {
                  date: newDate(1935, 11, 2),
                  racecourse: '根岸',
                  race: 'オールカマーハンデキャップ',
                  displayRace: 'オールカマーH',
                  distance: '2200',
                  grade: 'empire_cs',
                  entry: '7',
                  result: '5',
                },
                {
                  date: newDate(1935, 11, 3),
                  racecourse: '根岸',
                  race: '帝室御賞典',
                  displayRace: '帝室御賞典（横浜・秋）',
                  distance: '2000',
                  grade: 'empire_cup',
                  entry: '4',
                  result: '1',
                },
                {
                  date: newDate(1935, 11, 17),
                  racecourse: '根岸',
                  race: '呼馬優勝',
                  displayRace: '優勝',
                  distance: '2600',
                  grade: 'empire_cs',
                  entry: '6',
                  result: '1',
                },
                {
                  date: newDate(1935, 11, 25),
                  racecourse: '東京',
                  race: '目黒記念',
                  displayRace: '目黒記念（秋）',
                  distance: '3400',
                  grade: 'empire_grade',
                  entry: '5',
                  result: '1',
                },
                {
                  date: newDate(1935, 12, 6),
                  racecourse: '東京',
                  race: '農林省賞典',
                  displayRace: '連合二哩（秋）',
                  distance: '3200',
                  grade: 'empire_2mile',
                  entry: '6',
                  result: '1',
                },
                {
                  date: newDate(1936, 4, 3),
                  racecourse: '中山',
                  race: '中山四千米',
                  displayRace: '中山四千米',
                  distance: '4000',
                  grade: 'empire_grade',
                  entry: '3',
                  result: '1',
                },
                {
                  date: newDate(1936, 4, 18),
                  racecourse: '東京',
                  race: '各古馬特ハン',
                  displayRace: '特ハン',
                  distance: '2300',
                  grade: 'empire_cs',
                  entry: '10',
                  result: '2',
                },
                {
                  date: newDate(1936, 4, 25),
                  racecourse: '東京',
                  race: '目黒記念',
                  displayRace: '目黒記念（春）',
                  distance: '3400',
                  grade: 'empire_grade',
                  entry: '3',
                  result: '3',
                },
                {
                  date: newDate(1936, 5, 9),
                  racecourse: '根岸',
                  race: 'オールカマーハンデキャップ',
                  displayRace: 'オールカマーH',
                  distance: '2200',
                  grade: 'empire_cs',
                  entry: '11',
                  result: '6',
                },
                {
                  date: newDate(1936, 5, 17),
                  racecourse: '根岸',
                  race: '横浜特別',
                  displayRace: '横浜特別（春）',
                  distance: '3200',
                  grade: 'empire_grade',
                  entry: '8',
                  result: '2',
                },
                {
                  date: newDate(1936, 10, 10),
                  racecourse: '中山',
                  race: '古呼馬特ハン',
                  displayRace: '特ハン',
                  distance: '2200',
                  grade: 'empire_cs',
                  entry: '14',
                  result: '4',
                },
                {
                  date: newDate(1936, 11, 8),
                  racecourse: '根岸',
                  race: '横浜特別',
                  displayRace: '横浜特別（秋）',
                  distance: '3200',
                  grade: 'empire_grade',
                  entry: '7',
                  result: '4',
                },
                {
                  date: newDate(1936, 11, 23),
                  racecourse: '東京',
                  race: '目黒記念',
                  displayRace: '目黒記念（秋）',
                  distance: '3400',
                  grade: 'empire_grade',
                  entry: '7',
                  result: '4',
                },
                {
                  date: newDate(1936, 11, 29),
                  racecourse: '東京',
                  race: '五歳馬特別',
                  displayRace: '五歳馬特別（秋）',
                  distance: '2400',
                  grade: 'empire_grade',
                  entry: '8',
                  result: '8',
                },
              ],
            },
          ],
        },
      ],
    },
  ],
} as const satisfies Horse

export default FLORRIES_CUP
