import { Horse } from '@/types/Horse'
import { newDate } from 'app/lib/utils'
import { Foaled } from '@/types/Foaled'
import dynamic from 'next/dynamic'
const HL = dynamic(() => import('@/components/HorseLink'), { ssr: false })

const IRISH_EYES: Horse = {
  name: 'アイリツシユアイズ',
  pedigreeName: 'Irish Eyes',
  id: 'irish-eyes',
  foaled: new Foaled('1928'),
  died: '1947.05.10 難産斃死', // サラブレッド血統書 第3巻 p.1
  breeder: 'W. Booth, N.S.W.',
  owner: '下河邊牧場（千葉県印旛郡遠山村）',
  sex: 'female',
  sire: 'Treclare',
  dam: 'Liena',
  color: '鹿毛',
  netkeibaId: '000a0024c0',
  children: [
    {
      name: 'オホヒカリ',
      formerPedigreeName: '第参アイリツシユアイズ',
      id: 'ohohikari',
      breed: 'サラブレッド種',
      sex: 'female',
      color: '栗毛',
      foaled: new Foaled(newDate(1943, 4, 15)),
      died: '1967.04.27 死亡',
      sire: '月友',
      dam: 'アイリツシユアイズ',
      breeder: '下河邊牧場（北海道浦河郡浦河町）',
      owner: '栗林友二（大東牧場）',
      trainer: '尾形藤吉',
      jockey: '野平祐二',
      raceStats: {
        total: { runs: 31, wins: 10 },
        divisions: [
          { type: 'central', stats: { flat: { runs: 31, wins: 10 }, jump: { runs: 0, wins: 0 } } },
          { type: 'local', stats: { flat: { runs: 0, wins: 0 }, jump: { runs: 0, wins: 0 } } },
        ],
      },
      raceResults: [
        {
          date: newDate(1947, 4, 3),
          racecourse: '中山',
          race: '中山記念',
          displayRace: '中山記念（春）',
          distance: '2600',
          grade: 'jrs_grade',
          entry: '10',
          result: '3',
        },
        {
          date: newDate(1947, 6, 7),
          racecourse: '東京',
          race: '目黒記念',
          displayRace: '目黒記念（春）',
          distance: '3200',
          grade: 'jrs_grade',
          entry: '12',
          result: '2',
        },
        {
          date: newDate(1947, 10, 17),
          racecourse: '東京',
          race: '天皇賞',
          displayRace: '天皇賞（秋）',
          distance: '3200',
          grade: 'jrs_big8',
          entry: '6',
          result: '2',
        },
        {
          date: newDate(1947, 12, 7),
          racecourse: '中山',
          race: '中山記念',
          displayRace: '中山記念（秋）',
          distance: '3400',
          grade: 'jrs_grade',
          entry: '8',
          result: '5',
        },
      ],
      netkeibaId: '000a002645',
      children: [
        {
          name: 'クリノハナ',
          formerName: 'デンコウ',
          formerPedigreeName: 'オレゴン',
          id: 'kurinohana',
          breed: 'サラブレッド種',
          sex: 'male',
          color: '栗毛',
          foaled: new Foaled(newDate(1949, 5, 18)),
          died: '1965.09.29 敗血症',
          sire: 'プリメロ(GB)',
          dam: 'オホヒカリ',
          breeder: '大東牧場（千葉県印旛郡遠山村）',
          retired: '1953.03.05 蕃殖',
          owner: '栗林友二',
          trainer: '尾形藤吉',
          jockey: '八木沢勝美',
          raceStats: {
            total: { runs: 11, wins: 5 },
            divisions: [
              {
                type: 'central',
                stats: { flat: { runs: 11, wins: 5 }, jump: { runs: 0, wins: 0 } },
              },
              { type: 'local', stats: { flat: { runs: 0, wins: 0 }, jump: { runs: 0, wins: 0 } } },
            ],
          },
          prizeMoney: {
            total: '3,169,500円',
          },
          raceResults: [
            {
              date: newDate(1952, 4, 27),
              racecourse: '中山',
              race: '皐月賞',
              displayRace: '皐月賞',
              distance: '芝2000',
              grade: 'national_big8',
              entry: '14',
              result: '1',
            },
            {
              date: newDate(1952, 5, 25),
              racecourse: '東京',
              race: '東京優駿',
              displayRace: '東京優駿',
              distance: '芝2400',
              grade: 'national_big8',
              entry: '31',
              result: '1',
            },
            {
              date: newDate(1952, 9, 28),
              racecourse: '東京',
              race: 'セントライト記念',
              displayRace: 'セントライト記念',
              distance: '芝2400',
              grade: 'national_grade',
              entry: '7',
              result: '5',
            },
            {
              date: newDate(1952, 10, 26),
              racecourse: '中山',
              race: '中山記念',
              displayRace: '中山記念',
              distance: '芝2400',
              grade: 'national_grade',
              entry: '10',
              result: '7',
            },
          ],
          netkeibaId: '000a0008d8',
        },
        {
          name: 'クリノホシ',
          formerName: 'クリノカワ',
          formerPedigreeName: 'オホヒカリノ三',
          id: 'kurinohoshi',
          breed: 'サラブレッド種',
          sex: 'female',
          color: '鹿毛',
          foaled: new Foaled(newDate(1953, 5, 8)),
          died: '1977.11 死亡',
          sire: 'プリメロ(GB)',
          dam: 'オホヒカリ',
          breeder: '大東牧場（千葉県印旛郡遠山村）',
          owner: '栗林友二',
          raceStats: {
            total: { runs: 0, wins: 0 },
            divisions: [],
          },
          netkeibaId: '000a002a5e',
          children: [
            {
              name: 'クリカツラ',
              id: 'kurikatsura',
              breed: 'サラブレッド種',
              sex: 'female',
              color: '黒鹿毛',
              foaled: new Foaled(newDate(1962, 4, 21)),
              died: '1984.09 用途変更', // 血統書データベース
              sire: 'テイエポロ(ITY)',
              dam: 'クリノホシ',
              breeder: '大東牧場（千葉県印旛郡遠山村）', // 凪的電脳賽馬
              owner: '栗林友二',
              trainer: '大久保房松',
              jockey: '郷原洋行',
              raceStats: {
                total: { runs: 47, wins: 11 },
                divisions: [
                  {
                    type: 'central',
                    stats: { flat: { runs: 47, wins: 11 }, jump: { runs: 0, wins: 0 } },
                  },
                  {
                    type: 'local',
                    stats: { flat: { runs: 0, wins: 0 }, jump: { runs: 0, wins: 0 } },
                  },
                ],
              },
              prizeMoney: {
                total: '22,790,000円',
              },
              netkeibaId: '1955100312',
              children: [
                {
                  name: 'ライラックポイント',
                  id: 'lilac-point',
                  breed: 'サラブレッド種',
                  sex: 'female',
                  color: '黒鹿毛',
                  foaled: new Foaled(newDate(1979, 3, 26)),
                  died: '1997.12.29 死亡',
                  sire: 'マルゼンスキー',
                  dam: 'クリカツラ',
                  breeder: 'ユートピア牧場（北海道室蘭市）',
                  owner: '栗林友二',
                  trainer: '飯塚好次',
                  jockey: '的場均',
                  raceStats: {
                    total: { runs: 39, wins: 4 },
                    divisions: [
                      {
                        type: 'central',
                        stats: { flat: { runs: 39, wins: 4 }, jump: { runs: 0, wins: 0 } },
                      },
                      {
                        type: 'local',
                        stats: { flat: { runs: 0, wins: 0 }, jump: { runs: 0, wins: 0 } },
                      },
                    ],
                  },
                  prizeMoney: {
                    total: '45,164,000円',
                  },
                  raceResults: [
                    {
                      date: newDate(1981, 12, 12),
                      racecourse: '中山',
                      race: '3歳牝馬S(OP)',
                      displayRace: 'TV東京3歳牝馬S',
                      distance: '芝1600',
                      grade: 'jra_grade',
                      entry: '14',
                      result: '7',
                    },
                    {
                      date: newDate(1982, 5, 2),
                      racecourse: '東京',
                      race: '4歳牝馬特別(OP)',
                      displayRace: '4歳牝馬特別（東）',
                      distance: '芝1800',
                      grade: 'jra_grade',
                      entry: '17',
                      result: '7',
                    },
                    {
                      date: newDate(1982, 5, 23),
                      racecourse: '東京',
                      race: '優駿牝馬(OP)',
                      displayRace: '優駿牝馬',
                      distance: '芝2400',
                      grade: 'jra_big8',
                      entry: '24',
                      result: '17',
                    },
                    {
                      date: newDate(1983, 5, 15),
                      racecourse: '新潟',
                      race: '新潟大賞典(OP)',
                      displayRace: '新潟大賞典',
                      distance: '芝2000',
                      grade: 'jra_grade',
                      entry: '12',
                      result: '10',
                    },
                  ],
                  netkeibaId: '1979101622',
                  children: [
                    {
                      name: 'クリダリア',
                      id: 'kuri-dahlia',
                      breed: 'サラブレッド種',
                      sex: 'female',
                      color: '鹿毛',
                      foaled: new Foaled(newDate(1986, 3, 17)),
                      died: '2007.12.23 死亡',
                      sire: 'ニチドウアラシ',
                      dam: 'ライラックポイント',
                      breeder: 'ユートピア牧場（北海道登別市）',
                      owner: '栗林英雄',
                      trainer: '飯塚好次',
                      jockey: '的場均',
                      raceStats: {
                        total: { runs: 27, wins: 2 },
                        divisions: [
                          {
                            type: 'central',
                            stats: { flat: { runs: 27, wins: 2 }, jump: { runs: 0, wins: 0 } },
                          },
                          {
                            type: 'local',
                            stats: { flat: { runs: 0, wins: 0 }, jump: { runs: 0, wins: 0 } },
                          },
                        ],
                      },
                      prizeMoney: {
                        total: '43,652,600円',
                      },
                      raceResults: [
                        {
                          date: newDate(1988, 12, 17),
                          racecourse: '中山',
                          race: 'テレビ東京3歳牝馬S(GIII)',
                          displayRace: 'TV東京3歳牝馬S',
                          distance: '芝1600',
                          grade: 'jra_g3',
                          entry: '16',
                          result: '14',
                        },
                        {
                          date: newDate(1989, 1, 29),
                          racecourse: '東京',
                          race: 'デイリー杯クイーンC(GIII)',
                          displayRace: 'クイーンC',
                          distance: '芝1600',
                          grade: 'jra_g3',
                          entry: '9',
                          result: '5',
                        },
                        {
                          date: newDate(1989, 3, 18),
                          racecourse: '中山',
                          race: 'フラワーC(GIII)',
                          displayRace: 'フラワーC',
                          distance: '芝1800',
                          grade: 'jra_g3',
                          entry: '13',
                          result: '2',
                        },
                        {
                          date: newDate(1989, 4, 30),
                          racecourse: '東京',
                          race: 'サンスポ4歳牝馬特別(GII)',
                          displayRace: '4歳牝馬特別（東）',
                          distance: '芝2000',
                          grade: 'jra_g2',
                          entry: '16',
                          result: '7',
                        },
                        {
                          date: newDate(1989, 5, 21),
                          racecourse: '東京',
                          race: '優駿牝馬(GI)',
                          displayRace: '優駿牝馬',
                          distance: '芝2400',
                          grade: 'jra_g1',
                          entry: '24',
                          result: '16',
                        },
                        {
                          date: newDate(1989, 10, 1),
                          racecourse: '中山',
                          race: 'クイーンS(GIII)',
                          displayRace: 'クイーンS',
                          distance: '芝2000',
                          grade: 'jra_g3',
                          entry: '11',
                          result: '9',
                        },
                        {
                          date: newDate(1989, 10, 22),
                          racecourse: '福島',
                          race: 'カブトヤマ記念(GIII)',
                          displayRace: 'カブトヤマ記念',
                          distance: '芝1800',
                          grade: 'jra_g3',
                          entry: '11',
                          result: '11',
                        },
                        {
                          date: newDate(1989, 11, 5),
                          racecourse: '東京',
                          race: '根岸S(GIII)',
                          displayRace: '根岸S',
                          distance: 'ダ1400',
                          grade: 'jra_g3',
                          entry: '14',
                          result: '11',
                        },
                      ],
                      netkeibaId: '1986104818',
                    },
                    {
                      name: 'ライスシャワー',
                      id: 'rice-shower',
                      breed: 'サラブレッド種',
                      sex: 'male',
                      color: '黒鹿毛',
                      foaled: new Foaled(newDate(1989, 3, 5)),
                      died: '1995.06.04 予後不良',
                      sire: 'リアルシャダイ',
                      dam: 'ライラックポイント',
                      breeder: 'ユートピア牧場（北海道室蘭市）',
                      owner: '栗林英雄',
                      trainer: '飯塚好次',
                      jockey: '的場均',
                      raceStats: {
                        total: { runs: 25, wins: 6 },
                        divisions: [
                          {
                            type: 'central',
                            stats: { flat: { runs: 25, wins: 6 }, jump: { runs: 0, wins: 0 } },
                          },
                          {
                            type: 'local',
                            stats: { flat: { runs: 0, wins: 0 }, jump: { runs: 0, wins: 0 } },
                          },
                        ],
                      },
                      prizeMoney: {
                        total: '729,497,000円',
                      },
                      awards: [{ year: 1995, award: 'JRA特別賞' }],
                      raceResults: [
                        {
                          date: newDate(1991, 9, 1),
                          racecourse: '新潟',
                          race: '新潟3歳S(GIII)',
                          displayRace: '新潟3歳S',
                          distance: '芝1200',
                          grade: 'jra_g3',
                          entry: '14',
                          result: '11',
                        },
                        {
                          date: newDate(1992, 3, 29),
                          racecourse: '中山',
                          race: 'フジTVスプリングS(GII)',
                          displayRace: 'スプリングS',
                          distance: '芝1800',
                          grade: 'jra_g2',
                          entry: '14',
                          result: '4',
                        },
                        {
                          date: newDate(1992, 4, 19),
                          racecourse: '中山',
                          race: '皐月賞(GI)',
                          displayRace: '皐月賞',
                          distance: '芝2000',
                          grade: 'jra_g1',
                          entry: '17',
                          result: '8',
                        },
                        {
                          date: newDate(1992, 5, 10),
                          racecourse: '東京',
                          race: 'NHK杯(GII)',
                          displayRace: 'NHK杯',
                          distance: '芝2000',
                          grade: 'jra_g2',
                          entry: '16',
                          result: '8',
                        },
                        {
                          date: newDate(1992, 5, 31),
                          racecourse: '東京',
                          race: '東京優駿(GI)',
                          displayRace: '東京優駿',
                          distance: '芝2400',
                          grade: 'jra_g1',
                          entry: '18',
                          result: '2',
                        },
                        {
                          date: newDate(1992, 9, 27),
                          racecourse: '中山',
                          race: 'セントライト記念(GII)',
                          displayRace: 'セントライト記念',
                          distance: '芝2200',
                          grade: 'jra_g2',
                          entry: '13',
                          result: '2',
                        },
                        {
                          date: newDate(1992, 10, 18),
                          racecourse: '京都',
                          race: '京都新聞杯(GII)',
                          displayRace: '京都新聞杯',
                          distance: '芝2200',
                          grade: 'jra_g2',
                          entry: '10',
                          result: '2',
                        },
                        {
                          date: newDate(1992, 11, 8),
                          racecourse: '京都',
                          race: '菊花賞(GI)',
                          displayRace: '菊花賞',
                          distance: '芝3000',
                          grade: 'jra_g1',
                          entry: '18',
                          result: '1',
                        },
                        {
                          date: newDate(1992, 12, 27),
                          racecourse: '中山',
                          race: '有馬記念(GI)',
                          displayRace: '有馬記念',
                          distance: '芝2500',
                          grade: 'jra_g1',
                          entry: '16',
                          result: '8',
                        },
                        {
                          date: newDate(1993, 2, 21),
                          racecourse: '東京',
                          race: '目黒記念(GII)',
                          displayRace: '目黒記念',
                          distance: '芝2500',
                          grade: 'jra_g2',
                          entry: '12',
                          result: '2',
                        },
                        {
                          date: newDate(1993, 3, 21),
                          racecourse: '中山',
                          race: '日経賞(GII)',
                          displayRace: '日経賞',
                          distance: '芝2500',
                          grade: 'jra_g2',
                          entry: '12',
                          result: '1',
                        },
                        {
                          date: newDate(1993, 4, 25),
                          racecourse: '京都',
                          race: '天皇賞(春)(GI)',
                          displayRace: '天皇賞（春）',
                          distance: '芝3200',
                          grade: 'jra_g1',
                          entry: '15',
                          result: '1',
                        },
                        {
                          date: newDate(1993, 9, 19),
                          racecourse: '中山',
                          race: '産經賞オールカマー(GIII)',
                          displayRace: 'オールカマー',
                          distance: '芝2200',
                          grade: 'jra_g3',
                          entry: '13',
                          result: '3',
                        },
                        {
                          date: newDate(1993, 10, 31),
                          racecourse: '東京',
                          race: '天皇賞(秋)(GI)',
                          displayRace: '天皇賞（秋）',
                          distance: '芝2000',
                          grade: 'jra_g1',
                          entry: '17',
                          result: '6',
                        },
                        {
                          date: newDate(1993, 11, 28),
                          racecourse: '東京',
                          race: 'ジャパンC(GI)',
                          displayRace: 'ジャパンC',
                          distance: '芝2400',
                          grade: 'jra_g1',
                          entry: '16',
                          result: '14',
                        },
                        {
                          date: newDate(1993, 12, 26),
                          racecourse: '中山',
                          race: '有馬記念(GI)',
                          displayRace: '有馬記念',
                          distance: '芝2500',
                          grade: 'jra_g1',
                          entry: '14',
                          result: '8',
                        },
                        {
                          date: newDate(1994, 2, 13),
                          racecourse: '阪神',
                          race: '京都記念(GII)',
                          displayRace: '京都記念',
                          distance: '芝2200',
                          grade: 'jra_g2',
                          entry: '10',
                          result: '5',
                        },
                        {
                          date: newDate(1994, 3, 20),
                          racecourse: '中山',
                          race: '日経賞(GII)',
                          displayRace: '日経賞',
                          distance: '芝2500',
                          grade: 'jra_g2',
                          entry: '9',
                          result: '2',
                        },
                        {
                          date: newDate(1994, 12, 25),
                          racecourse: '中山',
                          race: '有馬記念(GI)',
                          displayRace: '有馬記念',
                          distance: '芝2500',
                          grade: 'jra_g1',
                          entry: '13',
                          result: '3',
                        },
                        {
                          date: newDate(1995, 2, 12),
                          racecourse: '京都',
                          race: '京都記念(GII)',
                          displayRace: '京都記念',
                          distance: '芝2200',
                          grade: 'jra_g2',
                          entry: '8',
                          result: '6',
                        },
                        {
                          date: newDate(1995, 3, 19),
                          racecourse: '中山',
                          race: '日経賞(GII)',
                          displayRace: '日経賞',
                          distance: '芝2500',
                          grade: 'jra_g1',
                          entry: '9',
                          result: '6',
                        },
                        {
                          date: newDate(1995, 4, 23),
                          racecourse: '京都',
                          race: '天皇賞(春)(GI)',
                          displayRace: '天皇賞（春）',
                          distance: '芝3200',
                          grade: 'jra_g1',
                          entry: '18',
                          result: '1',
                        },
                        {
                          date: newDate(1995, 6, 4),
                          racecourse: '京都',
                          race: '宝塚記念(GI)',
                          displayRace: '宝塚記念',
                          distance: '芝2200',
                          grade: 'jra_g1',
                          entry: '17',
                          result: '中',
                        },
                      ],
                      netkeibaId: '1989107699',
                    },
                  ],
                },
                {
                  name: 'リンカーンシア',
                  id: 'lincolnshire',
                  breed: 'サラブレッド種',
                  sex: 'female',
                  color: '黒鹿毛',
                  foaled: new Foaled(newDate(1980, 3, 20)),
                  died: '1987.02.13 死亡', // 血統書データベース
                  sire: 'ボイズイーボーイ(GB)',
                  dam: 'クリカツラ',
                  breeder: 'ユートピア牧場（北海道室蘭市）',
                  owner: '栗林英雄',
                  raceStats: {
                    total: { runs: 19, wins: 0 },
                    divisions: [
                      {
                        type: 'central',
                        stats: { flat: { runs: 18, wins: 0 }, jump: { runs: 1, wins: 0 } },
                      },
                      {
                        type: 'local',
                        stats: { flat: { runs: 0, wins: 0 }, jump: { runs: 0, wins: 0 } },
                      },
                    ],
                  },
                  prizeMoney: {
                    total: '9,240,000円', // JBIS
                  },
                  netkeibaId: '1980102115',
                  children: [
                    {
                      name: 'クリバロン',
                      id: 'kuri-baron',
                      breed: 'サラブレッド種',
                      sex: 'male',
                      color: '鹿毛',
                      foaled: new Foaled(newDate(1985, 4, 23)),
                      sire: 'タクラマカン',
                      dam: 'リンカーンシア',
                      breeder: '大東牧場（千葉県）',
                      retired: '1991.05.01 乗馬',
                      owner: '栗林英雄',
                      trainer: '橋口弘次',
                      jockey: '池添兼雄',
                      raceStats: {
                        total: { runs: 35, wins: 10 },
                        divisions: [
                          {
                            type: 'central',
                            stats: { flat: { runs: 14, wins: 1 }, jump: { runs: 21, wins: 9 } },
                          },
                          {
                            type: 'local',
                            stats: { flat: { runs: 0, wins: 0 }, jump: { runs: 0, wins: 0 } },
                          },
                        ],
                      },
                      prizeMoney: {
                        total: '141,697,000円',
                      },
                      raceResults: [
                        {
                          date: newDate(1989, 11, 26),
                          racecourse: '京都',
                          race: '京都大障害(秋)(重賞)',
                          displayRace: '京都大障害（秋）',
                          distance: '障3270',
                          grade: 'jra_jump',
                          entry: '8',
                          result: '7',
                        },
                        {
                          date: newDate(1990, 5, 5),
                          racecourse: '京都',
                          race: '京都大障害(春)(重賞)',
                          displayRace: '京都大障害（春）',
                          distance: '障3270',
                          grade: 'jra_jump',
                          entry: '11',
                          result: '9',
                        },
                        {
                          date: newDate(1990, 9, 15),
                          racecourse: '中京',
                          race: '中京障害S(重賞)',
                          displayRace: '中京障害S（秋）',
                          distance: '障3600',
                          grade: 'jra_jump',
                          entry: '10',
                          result: '7',
                        },
                        {
                          date: newDate(1990, 11, 24),
                          racecourse: '京都',
                          race: '京都大障害(秋)(重賞)',
                          displayRace: '京都大障害（秋）',
                          distance: '障3270',
                          grade: 'jra_jump',
                          entry: '7',
                          result: '1',
                        },
                        {
                          date: newDate(1991, 4, 6),
                          racecourse: '中山',
                          race: '中山大障害(重賞)',
                          displayRace: '中山大障害（春）',
                          distance: '障4100',
                          grade: 'jra_grandjump',
                          entry: '6',
                          result: '中',
                        },
                      ],
                      netkeibaId: '1985103631',
                    },
                  ],
                },
              ],
            },
            {
              name: 'クリユタカ',
              id: 'kuri-yutaka',
              breed: 'サラブレッド種',
              sex: 'male',
              color: '芦毛',
              foaled: new Foaled(newDate(1968, 5, 9)),
              sire: 'グレイモナーク(GB)',
              dam: 'クリノホシ',
              breeder: '大東牧場（千葉県）',
              owner: '栗林友二',
              trainer: '阿部正太郎',
              jockey: '郷原洋行→法理弘',
              raceStats: {
                total: { runs: 56, wins: 6 },
                divisions: [
                  {
                    type: 'central',
                    stats: { flat: { runs: 21, wins: 2 }, jump: { runs: 35, wins: 4 } },
                  },
                  {
                    type: 'local',
                    stats: { flat: { runs: 0, wins: 0 }, jump: { runs: 0, wins: 0 } },
                  },
                ],
              },
              prizeMoney: {
                total: '70,401,000円',
              },
              raceResults: [
                {
                  date: newDate(1973, 4, 8),
                  racecourse: '中山',
                  race: '中山大障害(OP)',
                  displayRace: '中山大障害（春）',
                  distance: '障4100',
                  grade: 'jra_grandjump',
                  entry: '6',
                  result: '3',
                },
                {
                  date: newDate(1973, 11, 23),
                  racecourse: '東京',
                  race: '東京障害特別(OP)',
                  displayRace: '東京障害特別（秋）',
                  distance: '障3300',
                  grade: 'jra_jump',
                  entry: '8',
                  result: '2',
                },
                {
                  date: newDate(1973, 12, 23),
                  racecourse: '中山',
                  race: '中山大障害(OP)',
                  displayRace: '中山大障害（秋）',
                  distance: '障4100',
                  grade: 'jra_grandjump',
                  entry: '12',
                  result: '1',
                },
                {
                  date: newDate(1974, 12, 22),
                  racecourse: '中山',
                  race: '中山大障害(OP)',
                  displayRace: '中山大障害（秋）',
                  distance: '障4100',
                  grade: 'jra_grandjump',
                  entry: '10',
                  result: '6',
                },
              ],
              netkeibaId: '1968z00180',
            },
            {
              name: 'クリホツト',
              id: 'kuri-hot',
              breed: 'サラブレッド種',
              sex: 'female',
              color: '鹿毛',
              foaled: new Foaled(newDate(1970, 5, 31)),
              died: '1989.08 用途変更', // 血統書データサービス
              sire: 'オンリーフオアライフ(GB)',
              dam: 'クリノホシ',
              breeder: '大東牧場（千葉県成田市）',
              owner: '今村正忠', // JBIS
              raceStats: {
                total: { runs: 4, wins: 0 },
                divisions: [
                  {
                    type: 'central',
                    stats: { flat: { runs: 4, wins: 0 }, jump: { runs: 0, wins: 0 } },
                  },
                  {
                    type: 'local',
                    stats: { flat: { runs: 0, wins: 0 }, jump: { runs: 0, wins: 0 } },
                  },
                ],
              },
              netkeibaId: '1955102326',
              children: [
                {
                  name: 'クリアミー',
                  id: 'kuri-amie',
                  breed: 'サラブレッド種',
                  sex: 'female',
                  color: '黒鹿毛',
                  foaled: new Foaled(newDate(1974, 4, 25)),
                  died: '1992.03.20 用途変更', // 血統書データサービス
                  sire: 'シーフユリユー(GB)',
                  dam: 'クリホツト',
                  breeder: '大東牧場（千葉県市原市）', // サラブレッド血統書 10巻 p.525
                  owner: '山本一夫', // JBIS
                  raceStats: {
                    total: { runs: 6, wins: 1 },
                    divisions: [
                      {
                        type: 'central',
                        stats: { flat: { runs: 6, wins: 1 }, jump: { runs: 0, wins: 0 } },
                      },
                      {
                        type: 'local',
                        stats: { flat: { runs: 0, wins: 0 }, jump: { runs: 0, wins: 0 } },
                      },
                    ],
                  },
                  prizeMoney: {
                    total: '3,070,000円', // JBIS
                  },
                  netkeibaId: '1955106006',
                  children: [
                    {
                      name: 'ブリージーラッド',
                      localName: 'ブリージーラツド',
                      id: 'breezy-lad',
                      breed: 'サラブレッド種',
                      sex: 'male',
                      color: '鹿毛',
                      foaled: new Foaled(newDate(1981, 3, 8)),
                      sire: 'ボールドラッド(USA)',
                      dam: 'クリアミー',
                      breeder: 'ユートピア牧場（北海道室蘭市）',
                      retired: '1988.05.11',
                      owner: '栗林英雄',
                      trainer: '秋谷元次（大井）→松田博資（栗東）',
                      jockey: '松本勉→小島貞博',
                      raceStats: {
                        total: { runs: 31, wins: 7 },
                        divisions: [
                          {
                            type: 'central',
                            stats: { flat: { runs: 2, wins: 0 }, jump: { runs: 13, wins: 4 } },
                          },
                          {
                            type: 'local',
                            stats: { flat: { runs: 16, wins: 3 }, jump: { runs: 0, wins: 0 } },
                          },
                        ],
                      },
                      prizeMoney: {
                        total: '105,665,400円',
                        central: '85,900,400円',
                        local: '19,765,000円',
                      },
                      raceResults: [
                        {
                          date: newDate(1983, 11, 24),
                          racecourse: '大井',
                          race: '青雲賞',
                          displayRace: '青雲賞（大井）',
                          distance: 'D1600',
                          grade: 'local_old_grade',
                          entry: '13',
                          result: '1',
                        },
                        {
                          date: newDate(1986, 3, 8),
                          racecourse: '阪神',
                          race: '阪神障害Ｓ（春）',
                          displayRace: '阪神障害S（春）',
                          distance: '障3200',
                          grade: 'jra_jump',
                          entry: '14',
                          result: '1',
                        },
                        {
                          date: newDate(1986, 5, 3),
                          racecourse: '京都',
                          race: '京都大障害（春）',
                          displayRace: '京都大障害（春）',
                          distance: '障3270',
                          grade: 'jra_jump',
                          entry: '10',
                          result: '2',
                        },
                        {
                          date: newDate(1987, 5, 9),
                          racecourse: '京都',
                          race: '京都大障害（春）',
                          displayRace: '京都大障害（春）',
                          distance: '障3270',
                          grade: 'jra_jump',
                          entry: '11',
                          result: '2',
                        },
                        {
                          date: newDate(1988, 3, 12),
                          racecourse: '阪神',
                          race: '阪神障害Ｓ（春）',
                          displayRace: '阪神障害S（春）',
                          distance: '障3200',
                          grade: 'jra_jump',
                          entry: '11',
                          result: '8',
                        },
                        {
                          date: newDate(1988, 4, 1),
                          racecourse: '東京',
                          race: '東京大障害',
                          displayRace: '東京大障害',
                          distance: '障4000',
                          grade: 'jra_grandjump',
                          entry: '10',
                          result: '中止',
                        },
                        {
                          date: newDate(1988, 5, 7),
                          racecourse: '京都',
                          race: '京都大障害（春）',
                          displayRace: '京都大障害（春）',
                          distance: '障3270',
                          grade: 'jra_jump',
                          entry: '12',
                          result: '8',
                        },
                      ],
                      netkeibaId: '1981100780',
                    },
                    {
                      name: 'クリヤング',
                      id: 'kuri-young',
                      breed: 'サラブレッド種',
                      sex: 'female',
                      color: '青鹿毛',
                      foaled: new Foaled(newDate(1982, 3, 6)),
                      died: '1996.10 用途変更', // 血統書データサービス
                      sire: 'ノーザンネイティヴ(CAN)',
                      dam: 'クリアミー',
                      breeder: 'ユートピア牧場（北海道室蘭市）', // JBIS
                      owner: '（有）ユートピア牧場', // JBIS
                      raceStats: {
                        total: { runs: 6, wins: 0 },
                        divisions: [
                          {
                            type: 'central',
                            stats: { flat: { runs: 6, wins: 0 }, jump: { runs: 0, wins: 0 } },
                          },
                          {
                            type: 'local',
                            stats: { flat: { runs: 0, wins: 0 }, jump: { runs: 0, wins: 0 } },
                          },
                        ],
                      },
                      prizeMoney: {
                        total: '660,000円', // JBIS
                      },
                      netkeibaId: '1982102140',
                      children: [
                        {
                          name: 'クリトライ',
                          id: 'kuri-try',
                          breed: 'サラブレッド種',
                          sex: 'male',
                          color: '青鹿毛',
                          foaled: new Foaled(newDate(1989, 4, 1)),
                          died: '1992. 廃用？',
                          sire: 'フォティテン(USA)',
                          dam: 'クリヤング',
                          breeder: 'ユートピア牧場（北海道室蘭市）',
                          retired: '1992.10.02 乗馬',
                          owner: '栗林英雄',
                          trainer: '阿部新生（美浦）',
                          raceStats: {
                            total: { runs: 10, wins: 2 },
                            divisions: [
                              {
                                type: 'central',
                                stats: { flat: { runs: 10, wins: 2 }, jump: { runs: 0, wins: 0 } },
                              },
                              {
                                type: 'local',
                                stats: { flat: { runs: 0, wins: 0 }, jump: { runs: 0, wins: 0 } },
                              },
                            ],
                          },
                          prizeMoney: {
                            total: '35,486,600円',
                          },
                          raceResults: [
                            {
                              date: newDate(1991, 9, 1),
                              racecourse: '新潟',
                              race: '新潟3歳S(GIII)',
                              displayRace: '新潟3歳S',
                              distance: '芝1200',
                              grade: 'jra_g3',
                              entry: '14',
                              result: '3',
                            },
                            {
                              date: newDate(1992, 4, 19),
                              racecourse: '中山',
                              race: '皐月賞(GI)',
                              displayRace: '皐月賞',
                              distance: '芝2000',
                              grade: 'jra_g1',
                              entry: '17',
                              result: '15',
                            },
                          ],
                          netkeibaId: '1989107691',
                        },
                        {
                          name: 'クリアモン',
                          id: 'kuri-amount',
                          breed: 'サラブレッド種',
                          sex: 'female',
                          color: '黒鹿毛',
                          foaled: new Foaled(newDate(1992, 3, 13)),
                          died: '2011.09.20 死亡', // 血統書データサービス
                          sire: 'バイアモン(USA)',
                          dam: 'クリヤング',
                          breeder: 'ユートピア牧場（北海道登別市）',
                          retired: '1996.03.22 繫殖', // 日付はJRA競走馬情報
                          owner: '（有）ユートピア牧場', // JBIS
                          trainer: '阿部新生（美浦）',
                          raceStats: {
                            total: { runs: 7, wins: 1 },
                            divisions: [
                              {
                                type: 'central',
                                stats: { flat: { runs: 7, wins: 1 }, jump: { runs: 0, wins: 0 } },
                              },
                              {
                                type: 'local',
                                stats: { flat: { runs: 0, wins: 0 }, jump: { runs: 0, wins: 0 } },
                              },
                            ],
                          },
                          prizeMoney: {
                            total: '7,750,000円', // JRA競走馬情報
                          },
                          netkeibaId: '1992109307',
                          children: [],
                        },
                      ],
                    },
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
  ],
}

export default IRISH_EYES
