import { Horse } from '@/types/Horse'
import { newDate } from 'app/lib/utils'
import { Foaled } from '@/types/Foaled'
import dynamic from 'next/dynamic'
const HL = dynamic(() => import('@/components/HorseLink'), { ssr: false })

const SCARLET_INK: Horse = {
  name: 'スカーレットインク',
  pedigreeName: 'Scarlet Ink',
  id: 'scarlet-ink',
  foaled: new Foaled('1971'),
  sex: 'female',
  breed: 'サラブレッド種',
  breeder: '米',
  sire: 'Crimson Satan',
  dam: 'Consentida',
  color: '栗毛',
  netkeibaId: '000a000768',
  raceStats: {
    total: {},
    divisions: [],
  },
  children: [
    {
      name: 'スカーレットローズ',
      englishName: 'Scarlet Rose',
      id: 'scarlet-rose',
      foaled: new Foaled(newDate(1987, 3, 8)), // コメント:1987年3月8日
      sex: 'female',
      breed: 'サラブレッド種',
      breeder: '社台ファーム（千歳市）',
      sire: 'ノーザンテースト(CAN)',
      dam: 'スカーレットインク',
      color: '栗毛',
      owner: '吉田照哉',
      trainer: '松山康久 (美浦)',
      netkeibaId: '1987105592',
      prizeMoney: {
        total: '1,960万円',
        central: '1,960万円',
        local: '0万円',
      },
      raceStats: {
        total: { runs: 14, wins: 2 },
        divisions: [],
      },
      children: [
        {
          name: 'スカーレットレディ',
          englishName: 'Scarlet Lady',
          id: 'scarlet-lady',
          foaled: new Foaled(newDate(1995, 5, 10)),
          sex: 'female',
          breed: 'サラブレッド種',
          breeder: 'ノーザンファーム（早来町）',
          sire: 'サンデーサイレンス(US)',
          dam: 'スカーレットローズ',
          color: '黒鹿毛',
          owner: '小金井惠雄',
          trainer: '松山康久 (美浦)',
          netkeibaId: '1995107900',
          prizeMoney: {
            total: '1,567万円',
            central: '1,567万円',
            local: '0万円',
          },
          raceStats: {
            total: { runs: 16, wins: 1 },
            divisions: [],
          },
          children: [
            {
              name: 'ヴァーミリアン',
              englishName: 'Vermilion',
              id: 'vermilion',
              foaled: new Foaled(newDate(2002, 4, 10)),
              sex: 'male',
              breed: 'サラブレッド種',
              breeder: 'ノーザンファーム（早来町）',
              sire: 'エルコンドルパサー',
              dam: 'スカーレットレディ',
              color: '黒鹿毛',
              owner: 'サンデーレーシング',
              trainer: '石坂正 (栗東)',
              netkeibaId: '2002100877',
              prizeMoney: {
                total: '113,285万円',
                central: '38,685万円',
                local: '74,600万円',
              },
              raceResults: [
                {
                  date: newDate(2010, 12, 5),
                  racecourse: '阪神',
                  race: 'ジャパンカップダート(GI)',
                  displayRace: 'ジャパンカップダート',
                  distance: 'ダ1800',
                  grade: 'jra_g1',
                  entry: '16',
                  result: '14',
                  favorite: '4',
                },
                {
                  date: newDate(2010, 6, 30),
                  racecourse: '大井',
                  race: '帝王賞競走(JpnI)',
                  displayRace: '帝王賞',
                  distance: 'ダ2000',
                  grade: 'nar_jpn1',
                  entry: '15',
                  result: '9',
                  favorite: '2',
                },
                {
                  date: newDate(2010, 1, 27),
                  racecourse: '川崎',
                  race: '川崎記念[指定交流](JpnI)',
                  displayRace: '川崎記念[指定交流]',
                  distance: 'ダ2100',
                  grade: 'nar_jpn1',
                  entry: '11',
                  result: '1',
                  favorite: '1',
                },
                {
                  date: newDate(2009, 12, 29),
                  racecourse: '大井',
                  race: '東京大賞典競走(GI)',
                  displayRace: '東京大賞典',
                  distance: 'ダ2000',
                  grade: 'nar_jpn1',
                  entry: '14',
                  result: '2',
                  favorite: '1',
                },
                {
                  date: newDate(2009, 12, 6),
                  racecourse: '阪神',
                  race: 'ジャパンカップダート(GI)',
                  displayRace: 'ジャパンカップダート',
                  distance: 'ダ1800',
                  grade: 'jra_g1',
                  entry: '16',
                  result: '8',
                  favorite: '2',
                },
                {
                  date: newDate(2009, 11, 3),
                  racecourse: '名古屋',
                  race: 'JBCクラシック(JpnI)',
                  displayRace: 'JBCクラシック',
                  distance: 'ダ1900',
                  grade: 'nar_jpn1',
                  entry: '12',
                  result: '1',
                  favorite: '1',
                },
                {
                  date: newDate(2009, 6, 24),
                  racecourse: '大井',
                  race: '帝王賞競走(JpnI)',
                  displayRace: '帝王賞',
                  distance: 'ダ2000',
                  grade: 'nar_jpn1',
                  entry: '13',
                  result: '1',
                  favorite: '1',
                },
                {
                  date: newDate(2009, 2, 22),
                  racecourse: '東京',
                  race: 'フェブラリーS(GI)',
                  displayRace: 'フェブラリーS',
                  distance: 'ダ1600',
                  grade: 'jra_g1',
                  entry: '16',
                  result: '6',
                  favorite: '2',
                },
                {
                  date: newDate(2008, 12, 29),
                  racecourse: '大井',
                  race: '東京大賞典競走(GI)',
                  displayRace: '東京大賞典',
                  distance: 'ダ2000',
                  grade: 'nar_jpn1',
                  entry: '10',
                  result: '2',
                  favorite: '1',
                },
                {
                  date: newDate(2008, 12, 7),
                  racecourse: '阪神',
                  race: 'ジャパンカップダート(GI)',
                  displayRace: 'ジャパンカップダート',
                  distance: 'ダ1800',
                  grade: 'jra_g1',
                  entry: '15',
                  result: '3',
                  favorite: '1',
                },
                {
                  date: newDate(2008, 11, 3),
                  racecourse: '園田',
                  race: 'JBCクラシック(JpnI)',
                  displayRace: 'JBCクラシック',
                  distance: 'ダ1870',
                  grade: 'nar_jpn1',
                  entry: '12',
                  result: '1',
                  favorite: '1',
                },
                {
                  date: newDate(2008, 3, 29),
                  racecourse: 'アラブ首長国連邦',
                  race: 'ドバイワールドC(GI)',
                  displayRace: 'ドバイワールドC',
                  distance: 'ダ2000',
                  grade: 'abroad_g1',
                  entry: '12',
                  result: '12',
                },
                {
                  date: newDate(2008, 2, 24),
                  racecourse: '東京',
                  race: 'フェブラリーS(GI)',
                  displayRace: 'フェブラリーS',
                  distance: 'ダ1600',
                  grade: 'jra_g1',
                  entry: '16',
                  result: '1',
                  favorite: '1',
                },
                {
                  date: newDate(2008, 1, 30),
                  racecourse: '川崎',
                  race: '川崎記念[指定交流](JpnI)',
                  displayRace: '川崎記念[指定交流]',
                  distance: 'ダ2100',
                  grade: 'nar_jpn1',
                  entry: '10',
                  result: '取',
                },
                {
                  date: newDate(2007, 12, 29),
                  racecourse: '大井',
                  race: '東京大賞典競走(GI)',
                  displayRace: '東京大賞典',
                  distance: 'ダ2000',
                  grade: 'nar_jpn1',
                  entry: '15',
                  result: '1',
                  favorite: '1',
                },
                {
                  date: newDate(2007, 11, 24),
                  racecourse: '東京',
                  race: 'ジャパンカップダート(GI)',
                  displayRace: 'ジャパンカップダート',
                  distance: 'ダ2100',
                  grade: 'jra_g1',
                  entry: '16',
                  result: '1',
                  favorite: '1',
                },
                {
                  date: newDate(2007, 10, 31),
                  racecourse: '大井',
                  race: 'JBCクラシック競走(JpnI)',
                  displayRace: 'JBCクラシック',
                  distance: 'ダ2000',
                  grade: 'nar_jpn1',
                  entry: '16',
                  result: '1',
                  favorite: '2',
                },
                {
                  date: newDate(2007, 3, 31),
                  racecourse: 'アラブ首長国連邦',
                  race: 'ドバイワールドC(GI)',
                  displayRace: 'ドバイワールドC',
                  distance: 'ダ2000',
                  grade: 'abroad_g1',
                  entry: '7',
                  result: '4',
                },
                {
                  date: newDate(2007, 1, 31),
                  racecourse: '川崎',
                  race: '川崎記念[指定交流](JpnI)',
                  displayRace: '川崎記念[指定交流]',
                  distance: 'ダ2100',
                  grade: 'nar_jpn1',
                  entry: '13',
                  result: '1',
                  favorite: '1',
                },
                {
                  date: newDate(2006, 12, 20),
                  racecourse: '名古屋',
                  race: '名古屋グランプリ指定(JpnII)',
                  displayRace: '名古屋グランプリ指定',
                  distance: 'ダ2500',
                  grade: 'nar_jpn2',
                  entry: '11',
                  result: '1',
                  favorite: '1',
                },
                {
                  date: newDate(2006, 11, 25),
                  racecourse: '東京',
                  race: 'ジャパンカップダート(GI)',
                  displayRace: 'ジャパンカップダート',
                  distance: 'ダ2100',
                  grade: 'jra_g1',
                  entry: '15',
                  result: '4',
                  favorite: '9',
                },
                {
                  date: newDate(2006, 5, 21),
                  racecourse: '中京',
                  race: '東海S(GII)',
                  displayRace: '東海S',
                  distance: 'ダ2300',
                  grade: 'jra_g2',
                  entry: '13',
                  result: '13',
                  favorite: '1',
                },
                {
                  date: newDate(2006, 3, 15),
                  racecourse: '船橋',
                  race: 'ダイオライト記念(JpnII)',
                  displayRace: 'ダイオライト記念',
                  distance: 'ダ2400',
                  grade: 'nar_jpn2',
                  entry: '10',
                  result: '1',
                  favorite: '1',
                },
                {
                  date: newDate(2006, 2, 19),
                  racecourse: '東京',
                  race: 'フェブラリーS(GI)',
                  displayRace: 'フェブラリーS',
                  distance: 'ダ1600',
                  grade: 'jra_g1',
                  entry: '16',
                  result: '5',
                  favorite: '3',
                },
                {
                  date: newDate(2006, 1, 22),
                  racecourse: '京都',
                  race: '平安S(GIII)',
                  displayRace: '平安S',
                  distance: 'ダ1800',
                  grade: 'jra_g3',
                  entry: '16',
                  result: '2',
                  favorite: '2',
                },
                {
                  date: newDate(2005, 12, 23),
                  racecourse: '名古屋',
                  race: '名古屋グランプリ指定(JpnII)',
                  displayRace: '名古屋グランプリ指定',
                  distance: 'ダ2500',
                  grade: 'nar_jpn2',
                  entry: '0',
                  result: '',
                },
                {
                  date: newDate(2005, 11, 30),
                  racecourse: '浦和',
                  race: '彩の国浦和記念(JpnII)',
                  displayRace: '彩の国浦和記念',
                  distance: 'ダ2000',
                  grade: 'nar_jpn2',
                  entry: '10',
                  result: '1',
                  favorite: '1',
                },
                {
                  date: newDate(2005, 9, 25),
                  racecourse: '阪神',
                  race: '神戸新聞杯(GII)',
                  displayRace: '神戸新聞杯',
                  distance: '芝2000',
                  grade: 'jra_g2',
                  entry: '13',
                  result: '10',
                  favorite: '8',
                },
                {
                  date: newDate(2005, 5, 7),
                  racecourse: '京都',
                  race: '京都新聞杯(GII)',
                  displayRace: '京都新聞杯',
                  distance: '芝2200',
                  grade: 'jra_g2',
                  entry: '15',
                  result: '12',
                  favorite: '3',
                },
                {
                  date: newDate(2005, 4, 17),
                  racecourse: '中山',
                  race: '皐月賞(GI)',
                  displayRace: '皐月賞',
                  distance: '芝2000',
                  grade: 'jra_g1',
                  entry: '18',
                  result: '12',
                  favorite: '7',
                },
                {
                  date: newDate(2005, 3, 20),
                  racecourse: '中山',
                  race: 'フジTVスプリングS(GII)',
                  displayRace: 'スプリングS',
                  distance: '芝1800',
                  grade: 'jra_g2',
                  entry: '16',
                  result: '14',
                  favorite: '2',
                },
                {
                  date: newDate(2004, 12, 25),
                  racecourse: '阪神',
                  race: 'ラジオたんぱ杯2歳S(GIII)',
                  displayRace: 'ラジオたんぱ杯2歳S',
                  distance: '芝2000',
                  grade: 'jra_g3',
                  entry: '9',
                  result: '1',
                  favorite: '2',
                },
              ],
              raceStats: {
                total: { runs: 34, wins: 15 },
                divisions: [],
              },
              children: [],
            },
          ],
        },
      ],
    },
  ],
}

export default SCARLET_INK
